### ISSUE TITLE
detectConnect: process not defined (node)

### ISSUE THREAD

**Issue by ryanleecode** [paritytech/capi#1008]
![image](https://github.com/paritytech/capi/assets/21375952/cc5118fc-018e-40e0-bb10-6636e0ec38a2)

![image](https://github.com/paritytech/capi/assets/21375952/e0f586ce-5934-49ad-89e2-77daf5259be0)

**Comment by ryanleecode** [comment]
I think the problem is this needs to happen at compile time for browsers because it can't happen at runtime

**Comment by harrysolovay** [comment]
Yea: might need to use bundler-specific tools to swap out the env var occurrence with the actual value. For instance...

- with CRA: https://create-react-app.dev/docs/adding-custom-environment-variables/
- with Vite: https://vitejs.dev/guide/env-and-mode.html
- with Rollup: https://www.npmjs.com/package/rollup-plugin-inject-process-env

**Comment by ryanleecode** [comment]
We may want to consider a Capi global object (with types injected to global.d.ts) or equivalent. then in the browser one can call

```ts
Capi.setTarget(import.meta.env.CAPI_TARGET)
```

**Comment by kratico** [comment]
This is bundler specific and we will add recipes for `webpack` and `vite`.

**Comment by ryanleecode** [comment]
smart thinking. I like it Matias, should we document it somewhere in capi -- like BROWSER.md?

**Comment by harrysolovay** [comment]
Best to add it to the WIP manual (I'll do so)

**Comment by kratico** [comment]
@SaltyCucumber the `process.env.` issue depends on your `nets.ts` file.

You need a Capi server, if you do `import { westend } from "@capi/westend"` and your `nets.ts` file is something like
```ts
import { bins, net } from "capi"

const bin = bins({
  polkadot: ["polkadot", "v0.9.38"],
})

export const westend = net.dev({
  bin: bin.polkadot,
  chain: "westend-dev",
})
```

However, you don't need a Capi server, if your `nets.ts` file is something like
```ts
import { net } from "capi"
export const westend = net.ws({
  url: "wss://westend-rpc.polkadot.io/",
})
``` 

**How to start a Capi server for the bundler?**

In your package.json

```json
  "scripts": {
    "dev:vite": "capi serve -- vite",
    "dev:webpack": "capi serve -- webpack --config webpack.config.js",
  }
```

The above will start a Capi server and spawn the bundler with the `CAPI_SERVER` and `CAPI_TARGET` environment variables.

Alternatively, a Capi server could be started in a separately with `capi serve`.

The default url is `http://localhost:4646` and it could passed to the bundler like

```
CAPI_SERVER=http://localhost:4646 webpack --config webpack.config.js
```

**Comment by kratico** [comment]
@SaltyCucumber I was able to get the `webpack.DefinePlugin` to set `process.env.`.
The following works
```
  plugins: [
    new webpack.DefinePlugin({
      process: {
        env: {
          CAPI_SERVER: JSON.stringify(process.env.CAPI_SERVER),
          CAPI_TARGET: JSON.stringify(process.env.CAPI_TARGET),
        }
      }
    }),
```

But the following doesn't
```
  plugins: [
    new webpack.DefinePlugin({
      "process.env.CAPI_SERVER": JSON.stringify(process.env.CAPI_SERVER),
      "process.env.CAPI_TARGET": JSON.stringify(process.env.CAPI_TARGET),
    }),
```

I created https://github.com/paritytech/capi/issues/1030 to discuss an alternative.
