### ISSUE TITLE
Sync with a local substrate faulty codegen

### ISSUE THREAD

**Issue by SaltyCucumber** [paritytech/capi#1033]
When running capi sync with a local substrate generates a faulty codegen

script from package.json
```
"sync": "capi sync node --runtime-config package.json --server https://capi.dev"
```

nets.ts
```
export const local = net.ws({
  url: 'ws://127.0.0.1:9944',
});
```

https://capi.dev/@v0.1.0-beta.40/7d699789a4e7565d/local.tar
```
Error: Expected '{', got 'namespace' at types.d.ts:6063:8

  export namespace PalletCoreFellowshipCall {
         ~~~~~~~~~
    at Object.formatText (https://deno.land/x/dprint@0.2.0/mod.ts:246:17)
    at file:///src/server/codegenHandler.ts:170:39
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async Promise.all (index 0)
    at async file:///src/server/codegenHandler.ts:156:7
    at async S3Cache._getRaw (file:///src/util/cache/s3.ts:18:19)
    at async handleTarball (file:///src/server/codegenHandler.ts:149:21)
    at async Server.<anonymous> (file:///src/server/errorHandler.ts:6:14)
    at async Server.#respond (https://deno.land/std@0.186.0/http/server.ts:299:18)
   ```
   
   Capi: beta 40
   Node: 20

**Comment by kratico** [comment]
@SaltyCucumber Could you share the node code?
The code gen uses the node metadata to generate the code to interact with the node.

**Comment by SaltyCucumber** [comment]
@kratico the dex-pallet branch was merged to master
so I'm just using the latest substrate master
codegen still broken with same error
https://capi.dev/@v0.1.0-beta.40/793ae14f3bc8ecf7/local.tar

**Comment by kratico** [comment]
It seems that the issue is related to a reserved keyword being used inside the `PalletCoreFellowshipCall` generated code

```ts
export namespace PalletCoreFellowshipCall {  
            // ...

            export type import = ({ type: "import" , })
            export function import<X>(): C.ValueRune<PalletCoreFellowshipCall.import, C.RunicArgs.U<X>>
            export function isimport(value: PalletCoreFellowshipCall): value is PalletCoreFellowshipCall.import
          
}
```

These are the errors
- `Type alias name cannot be 'import'.deno-ts(2457)`
- `Identifier expected. 'import' is a reserved word that cannot be used here.deno-ts(1359)`

<img width="1149" alt="image" src="https://github.com/paritytech/capi/assets/1209171/19deb662-1a9f-44e1-9460-794c7670ca32">

**Comment by SaltyCucumber** [comment]
I "fixed" it on the Substrate side, but devs say it should be dealt with from capi side
@kratico any estimates or ideas on how this can be tackled?

**Comment by kratico** [comment]
This is a bug in the codegen and I would suggest to wait for @harrysolovay input.

I did a few attempts to fix this without success.

**Comment by harrysolovay** [comment]
Strange that it's lower-cased. `Import` wouldn't be a problem.
