### ISSUE TITLE
Creating Calls from `callData`

### ISSUE THREAD

**Issue by peetzweg** [paritytech/capi#1036]
## Feature Request

Allow recreation of a call from hex encoded `call data`. 

### Suggestion

``ExtrinsicRune.from(callData: Uint8Array | `0x{string}`)``

### Motivation

Building UIs we often just have access to hex encoded call data. It would be great to recreate an Call object from it which an be inspected to create UIs showing the actual extrinsic structure in a human readable format.

### Use Cases

A proposed extrinsic call of a multisig has been saved as `call data` in a database for later retrieval. I need to recreate the `ExtrinsicRune` from this `call data` in order to use it with capi.

**Comment by peetzweg** [comment]
This ticket or #1037 is actually blocking a sane implementation of https://github.com/paritytech/capi-multisig-app/issues/173.

cc @kratico or @ryanleecode any ideas how to do this?

**Comment by peetzweg** [comment]
Okay I can create a `RuntimeCall` to be used with `multisig.ratify(user,call)` using the `$runtimeCall` codec. 👍 

```
$runtimeCall.decode(hex.decode(callData))
```

I don't need to convert into an `ExtrinsicRune` though but how would this be done? And how to properly inspect a `RuntimeCall`. Hm.

**Comment by harrysolovay** [comment]
Just added some convenience methods in #1044. @peetzweg does this help?

**Comment by peetzweg** [comment]
I don't need an actual ExtrinsicsRune for my use case with the multisig.ratify right now. Can't tell if this is ever needed or useful. I guess you are in the best position to jugdge that.

In general it feels good to be able to construct Runes via .fromHex or .fromString or so.

**Comment by harrysolovay** [comment]
#1044 has been merged
