### ISSUE TITLE
Creating nft collection using capi

### ISSUE THREAD

**Issue by SaltyCucumber** [paritytech/capi#1048]
My code goes like this
```
          const sender = pjsSender(local, activeWallet.signer as PjsSigner);

          const createEvents = await local.Nfts.create({
            config: collectionConfig,
            admin: MultiAddress.Id(ss58.decode(activeAccount.address)[1]),
          })
            .signed(
              signature({
                sender: sender(activeAccount.address),
              }),
            )
            .sent()
            .dbgStatus('Create collection:')
            .finalizedEvents()
            .run();
```

1. I need a type assertion for PjsSigner to avoid TS errors
I'm using a Signer type from @polkadot/types which has signPayload parameter as optional, while PjsSigner's signPayload is mandatory.

2. when executing the code I get an error
`pjs signer: unknown extension ChargeAssetTxPayment`

in capi => pjs_sender => convertExtensionCodec I can add a dirty hack and the execution goes further
```
if (key === 'ChargeAssetTxPayment') {
    return $.field('ChargeAssetTxPayment', $pjs(value));;
}
```

3. Is there a better way to convert wallet address string (received from extension) into MultiAddress? And why the difference in formats for admin and sender? Maybe there should be only one and used for both on capi side?

**Comment by SaltyCucumber** [comment]
Ok, I found the second issue
```
const pjsExtraKeyMap: Record<string, string> = {
  CheckEra: "era",
  CheckMortality: "era",
  ChargeTransactionPayment: "tip",
  CheckNonce: "nonce",
}
```
pjs_sender is missing ChargeAssetTxPayment

**Comment by tjjfvi** [comment]
PJS has arbitrary hard-coded alternate formats for the extrinsic extra & additional, so in the pjs compat pattern we need to duplicate those transformations. Looks like we were indeed missing `ChargeAssetTxPayment`. We should have all of them as of #1105, though. I also fixed the typing, so you shouldn't need the cast anymore.

**Comment by SaltyCucumber** [comment]
> PJS has arbitrary hard-coded alternate formats for the extrinsic extra & additional, so in the pjs compat pattern we need to duplicate those transformations. Looks like we were indeed missing `ChargeAssetTxPayment`. We should have all of them as of #1105, though. I also fixed the typing, so you shouldn't need the cast anymore.

Great to hear, I'll check it out later, thanks @tjjfvi
