### ISSUE TITLE
breaking metadata changes always require a new release of capi

### ISSUE THREAD

**Issue by ryanleecode** [paritytech/capi#1052]
Whenever there is a breaking metadata change -- transactions usually result in `ServerError: Invalid Transaction` ... `Transaction has a bad signature`. This is a problem because we need to re-release capi with the updated metadata and force uses to update. Users on existing versions of capi will see their applications immediately broken... Not ideal for DX especially if you were building  a capi app at a hackathon and then went to demo only to see it stop working at no fault of your own. 

See https://github.com/paritytech/capi/issues/961 for previous occurences

**Comment by tjjfvi** [comment]
No one should be depending on the metadata capi uses, so when there is a breaking metadata change, users should only have to rerun `capi sync`.

I'm not sure we have an issue for this, but it might be worthwhile to rename capi's codegen dependencies to avoid it being easy for users to accidentally depend on our codegen.
