### ISSUE TITLE
Bundle size too large due to dev users

### ISSUE THREAD

**Issue by statictype** [paritytech/capi#1053]
~3.5MB of the minified and gzipped production bundle size comes from dev users public keys artifact, without actually importing any dev users in the project. Looks like a regression of https://github.com/paritytech/capi/issues/951

The reasoning behind this approach of creating 100k users for testing is not clear to me.

<img width="2831" alt="Screenshot 2023-06-09 at 13 17 47" src="https://github.com/paritytech/capi/assets/42985153/6de085c4-1e3a-45d9-8e71-265c6984a4e0">

**Comment by tjjfvi** [comment]
On another note, you might be happy to hear that the second-largest rectangle there (`capi_crypto_wrappers.generated.js`) will be gone as of #1060

**Comment by statictype** [comment]
i just wonder what was the issue you encountered which led you to conclude there is a need for many different users.
the default dev accounts seem to be sufficient for all testing needs i know of.
is restarting the dev chain not possible? or transferring smaller amounts to prevent running out of balance? set the initial balance of default dev accounts to max `u128`? sudo set balance before all tests?

**Comment by tjjfvi** [comment]
If two different tests running in parallel use the same test users, they will attempt to send two extrinsics with the same nonce, which will result in one of the two failing.

**Comment by statictype** [comment]
finding a way to increment the nonce sounds like a better way to go than generating 100k test users, imho
i am sure this is possible.
