### ISSUE TITLE
Local development with `capi serve` impossible - memory leak?

### ISSUE THREAD

**Issue by statictype** [paritytech/capi#1054]
When trying to work with a local binary via capi on an Intel Mac, memory usage grows indefinitely.

Tried with the `capi:dev` command as defined here [here](https://github.com/paritytech/capi-multisig-app/pull/213) on a `2,2 GHz 6-Core Intel Core i7` MacBook Pro with node `v20.0.0`

https://github.com/paritytech/capi/assets/42985153/a6eab2ca-db07-4408-951a-d69138ce9d04

**Comment by tjjfvi** [comment]
I'm not able to reproduce; can you give steps to reproduce? (`capi-multisig-app` commit sha, working directory, command to run, ...)

**Comment by kratico** [comment]
For me, it works locally with `node@v20.1.0`

**Comment by tjjfvi** [comment]
Same here. @statictype @peetzweg Can you try updating and see if it also fixes it for you?
