### ISSUE TITLE
`esm/main.js` errors with `pnpm` if `ts-node` is not installed in the top level package

### ISSUE THREAD

**Issue by kratico** [paritytech/capi#1066]
When `pnpm` is used as a dependency manager, `ts-node` can not be found unless it is added as dependency.

Note: `ts-node` is set as `capi` `npm` dependency but `./node_modules/.bin/capi` does not resolve the `ts-node` dependency.

<img width="1009" alt="image" src="https://github.com/paritytech/capi/assets/1209171/19cc9e6e-e0c7-43c4-bf3e-c3d6a2f37137">

**Comment by tjjfvi** [comment]
Fixed by #1095
