### ISSUE TITLE
Subpath export type declarations cannot be found

### ISSUE THREAD

**Issue by kratico** [paritytech/capi#1088]
The following import does not resolve its type declarations

```
import { net } from "capi/nets"
```

![image](https://github.com/paritytech/capi/assets/1209171/56483e6b-7814-4e85-a30d-3c0cd13c0177)

Rewriting the subpath export seems to fix the issue

<img width="1034" alt="image" src="https://github.com/paritytech/capi/assets/1209171/851b6721-e30b-481d-8604-33cfe8717af1">

**Comment by tjjfvi** [comment]
So #1086 didn't fix this?

**Comment by harrysolovay** [comment]
It seemingly did. Beta 47's NPM pkg exports contains the following.

```json
"./nets": {
  "import": {
    "types": "./types/nets/mod.d.ts",
    "default": "./esm/nets/mod.js"
  },
  "require": {
    "types": "./types/nets/mod.d.ts",
    "default": "./script/nets/mod.js"
  }
},
```

Created a new Capi + NodeJS project and the types seem to be loading fine from my end. @kratico any chance you could share a repro?

**Comment by kratico** [comment]
Nevertheless, given that there is no type differences between `esm` and `cjs`, the exports could be simplified to 
```
"./nets": {
  "types": "./types/nets/mod.d.ts",
  "import": "./esm/nets/mod.js",
  "require": "./script/nets/mod.js"
},
```

Thoughts?

**Comment by harrysolovay** [comment]
I don't think we should further complicate our dnt task... I could see that suggestion going in the dnt issues though. I'd imaging they'll be amenable to this suggestion.

**Comment by kratico** [comment]
Fixed by updating the `tsconfig.json` to check `nets.ts`

For example,

```
{
  "extends": "./tsconfig.base.json",
  "files": [
    "nets.ts"
  ],
  ...
}
```
