### ISSUE TITLE
Generating RPC Types From Metadata (Once Reflected)

### ISSUE THREAD

**Issue by harrysolovay** [paritytech/capi#109]
We currently hand-type RPC methods in [`rpc/messages.ts`](https://github.com/paritytech/capi/blob/7202f6e09d1c58e5b4eddb5c14862ba853acb8f7/rpc/messages.ts#L47). This is error-prone, as we'll need expend ongoing manual effort to keep these declarations in sync with the Rust source of truth. Also, we want to enable different combinations of these methods / custom methods depending on specified chain (related to #108).

An ideal solution would involve generating these type-level lookups. Aka. something akin to FRAME metadata, but for RPC definitions.

Thoughts on this @niklasad1?

**Comment by niklasad1** [comment]
It's really tricky because these rpc's can be defined in so many places in substrate, frame, runtime APIs and similar.

Ideally, I would want to have a method e.g.  `"rpc_methods/rpc.discover"` to have all information from a node which RPC methods it exposes to generate the RPC API with parameters and return types.

There is this https://spec.open-rpc.org/#openrpc-document which is a standard how to this in JSON-RPC v2 which looks cool
but we haven't looked into it and how well it works with all the generics stuff in substrate.

**Comment by harrysolovay** [comment]
> There is this https://spec.open-rpc.org/#openrpc-document which is a standard how to this in JSON-RPC v2 which looks cool

This spec looks fantastic; in fact, it seems [trpc](https://github.com/trpc/trpc)––a popular TS dev tool––[complies](https://github.com/trpc/trpc/pull/532) with the OpenRPC specification. **Very promising**.

As we build out more libraries, utilizing a single source of truth for RPC types (and devising an approach to handle variation across chains) will become a necessity. The `rpc.discover` method would address this need quite well; it would even enable the generation of narrow typings for errors of each method.

I can imagine that this would entail a non-trivial amount of work. Perhaps a first pass could omit the method result content descriptors / reference objects. Meanwhile, params are usually just numbers / hex-encoded strings; these would be simpler to represent than the complex generic types of Substrate.

^ might not be helpful, just hoping to get the ball rolling. Let me know if I should transfer this issue to one of your repos. Might make for a good backlog item.

**Comment by niklasad1** [comment]
we already got an issue for that https://github.com/paritytech/jsonrpsee/issues/737 but just a matter to get someone working on it :)

**Comment by tjjfvi** [comment]
We'll be using `state_call`, so we won't need these types.
