### ISSUE TITLE
`ReferenceError: crypto is not defined` on node

### ISSUE THREAD

**Issue by josepot** [paritytech/capi#1132]
In order to use CAPI on node I must have the following code at the very beginning:

```ts
import crypto from 'crypto'
(globalThis as any).crypto = crypto
```

Otherwise, I get the following error:

```
        Object.defineProperty(this, "id", { value: marker + crypto.randomUUID() });
                                                            ^

ReferenceError: crypto is not defined
```

**Comment by ryanleecode** [comment]
What version of node are you running? Capi requires node 20+

**Comment by josepot** [comment]
> What version of node are you running? Capi requires node 20+

Thanks! It does work on Node 20.

I was using node 18 (which is currently [the Active LTS](https://github.com/nodejs/release#release-schedule)). It feels a bit much to require the very latest "current" release, but I guess that it's fair game. Although, I didn't see any mention of this in the docs? Perhaps I missed it, though. However, if I didn't miss it, then I think that it would be a good idea to document this. I think that most developers assume libraries to work with the Active LTS releases, unless it's stated otherwise, ofc.

**Comment by ryanleecode** [comment]
We had a similar issue before https://github.com/paritytech/capi/issues/1003, i think it has to do with the web crypto apis being experimental or stable. Its not our goal to force users to use the current release of node, but it is a circumstantial pain point since we are going from Deno -> Node -> Browser and there are transpilational issues along the way.

**Comment by tjjfvi** [comment]
> However, if I didn't miss it, then I think that it would be a good idea to document this

https://github.com/paritytech/docs.capi.dev/pull/17
