### ISSUE TITLE
Error types

### ISSUE THREAD

**Issue by statictype** [paritytech/capi#1133]
Not clear how to handle errors in a type safe way.
If I run the multisig ratify call as in the [example](https://github.com/paritytech/capi/blob/main/examples/tx/handle_errors.eg.ts) i get back `any`

<img width="449" alt="Screenshot 2023-07-05 at 19 58 24" src="https://github.com/paritytech/capi/assets/42985153/9163f3fe-9b3b-4e37-a0f8-3eaa7dc6c257">

**Comment by ryanleecode** [comment]
You'll need to supply a callback to rehandle

```ts
  const ratifyCall2 = multisig
    .ratify(user, call)
    .signed(signature({ sender }))
    .sent()
    .dbgStatus("Ratify")
    .finalizedEvents()
    .unhandleFailed()
    .rehandle(is(ExtrinsicError), () => Rune.constant("aaa"))
    .run()
```

![image](https://github.com/paritytech/capi/assets/21375952/42105514-d11c-40c5-b2f8-c9263b1e9d47)

**Comment by statictype** [comment]
how should a user know that?

**Comment by harrysolovay** [comment]
Rehandling doesn't require a fallback. In the case that it's left blank, it will simply move the matched value back into the U track. @statictype would the following API be preferable?

```ts
const sent = multisig
  .ratify(user, call)
  .signed(signature({ sender }))
  .sent()
  .dbgStatus("Ratify")

const [finalizedEvents, finalizedErrors] = Rune
  .tuple([
    sent.finalizedEvents(),
    sent.finalizedErrors(),
  ])
  .run()
```

> Note: `finalizedEvents` would contain the raw system extrinsic failed events. `finalizedErrors` would contain them, but decoded according to the FRAME metadata.

Would this simplify things for you?
