### ISSUE TITLE
Rehandle and events

### ISSUE THREAD

**Issue by statictype** [paritytech/capi#1134]
Not clear how to do something with the emitted events while also re-handling errors.
If this is not a desired flow, it should not be possible to write the code.

The following code, although correct, produces an error at runtime if the transaction failed.

```ts
  const ratifyCall = multisig
    .ratify(user, call)
    .signed(signature({ sender }))
    .sent()
    .dbgStatus("Ratify")
    .finalizedEvents()
    .unhandleFailed()
    .rehandle(is(ExtrinsicError))
    .pipe(filterPureCreatedEvents)

  await ratifyCall.run()
```

<img width="672" alt="Screenshot 2023-07-05 at 20 23 15" src="https://github.com/paritytech/capi/assets/42985153/80c9ab17-bd5d-4cbc-a8d5-5f271a7f0584">
    

---

The following code appears to run successfully although there was an error

```ts
  const ratifyCall = multisig
    .ratify(user, call)
    .signed(signature({ sender }))
    .sent()
    .dbgStatus("Ratify")
    .finalizedEvents()
    .unhandleFailed()
    .pipe(filterPureCreatedEvents)
    .rehandle(is(ExtrinsicError))

  await ratifyCall.run()
```

<img width="653" alt="Screenshot 2023-07-05 at 20 29 22" src="https://github.com/paritytech/capi/assets/42985153/ec12c0b3-cb10-496e-acdd-147b0879658c">

https://westend.subscan.io/block/0x6d71bb09f5c597518bd856ede5abc9fff28b753bc264f8e479bced248ef134ab

**Comment by ryanleecode** [comment]
likely missing the callback in `rehandle` as mentioned in https://github.com/paritytech/capi/issues/1133

**Comment by statictype** [comment]
please make sure the examples are up to date

**Comment by harrysolovay** [comment]
It's supposed to work without a callback (@ryanleecode).
