### ISSUE TITLE
misc. feedback

### ISSUE THREAD

**Issue by harrysolovay** [paritytech/capi#1175]
- confusion as to why the `blockHash` method call proceeds the `block` call –– open it up for debate + explain current reasoning
- justify handle/unhandle/rehandle + more concrete examples
- provide instructions on local codegen server + make [capi.dev FAQ](https://docs.capi.dev/faq/why-capi-dev) more visible

**Comment by vjjft** [comment]
*added:*
- https://github.com/paritytech/capi/issues/1183
- https://github.com/paritytech/capi/issues/1184
- https://github.com/paritytech/capi/issues/1185
