### ISSUE TITLE
delete add-to-project workflow

### ISSUE THREAD

**Issue by tjjfvi** [paritytech/capi#1193]
https://github.com/paritytech/capi/blob/main/.github/workflows/add_to_project.yml

Rendered unnecessary by 'project workflows'
<img width="957" alt="image" src="https://github.com/paritytech/capi/assets/44031566/82db3a79-5469-4eaf-b2a1-38c58e612cee">

**Comment by vjjft** [comment]
Given:

![image](https://github.com/paritytech/capi/assets/18031950/54a8d0cd-5fb2-4f12-9bce-39c5df5e249f)

we will use this custom workflow for other repos, if not all repos
