### ISSUE TITLE
feature request: decode and encode address utilities

### ISSUE THREAD

**Issue by karl-kallavus** [paritytech/capi#174]
Kindly request for `@polkadot/keyring` utils analogs, e.g `decodeAddress(address)`, `encodeAddress(address)`

**Comment by harrysolovay** [comment]
@karl-kallavus can you please rephrase + add more info?

**Comment by karl-kallavus** [comment]
@harrysolovay maybe [this documentation](https://polkadot.js.org/docs/keyring/start/ss58#how-is-the-encoding-done)  could help, [decode test cases](https://github.com/polkadot-js/common/blob/3597a4eb4e0cf9985104568058c5cd23701bbaed/packages/util-crypto/src/address/decode.spec.ts) and [encode test cases](https://github.com/polkadot-js/common/blob/3597a4eb4e0cf9985104568058c5cd23701bbaed/packages/util-crypto/src/address/encode.spec.ts)

**Comment by harrysolovay** [comment]
I believe this was addressed by #194 (see implementation [here](https://github.com/paritytech/capi/blob/b59ef2cde5c9316b4332297c6e2e5b6e47eddabc/ss58/mod.ts)). Is this what you are describing?

**Comment by karl-kallavus** [comment]
Works fine! Thank you guys! Closing this PR!
