### ISSUE TITLE
Missing RPC state_traceBlock

### ISSUE THREAD

**Issue by xlc** [paritytech/capi#178]

**Comment by harrysolovay** [comment]
The method is accessible, but the params & result are `any`-typed (see [here](https://github.com/paritytech/capi/blob/60db2dad1c94835ef709ae595865336827ea9da6/known/rpc.ts#L157)). You can try it out in [this playground file](https://github.com/paritytech/capi/blob/60db2dad1c94835ef709ae595865336827ea9da6/examples/rpc/call.ts) if you'd like. Hopefully we can focus on narrowing types soon. In the meantime, PRs are more than welcome.

Linking to #127
