### ISSUE TITLE
Rework `RpcClient`/beacon system into wrapper type with open/reconnect/close methods

### ISSUE THREAD

**Issue by tjjfvi** [paritytech/capi#19]
[Moved from <https://github.com/paritytech/capi/pull/17#discussion_r884260131>]

I think having to continually pass around two different things to everything that wants an RPC is rather messy, and since opening/reconnecting/closing needs to happen under the hood, I think there should be a type that wraps `RpcClient` with open/reconnect/close methods, rather than punting two parameters around everywhere.

At that point, we could largely remove the concept of a beacon from the various effects, and simply have something like:
```ts
const rpc = wsRpc(POLKADOT_RPC_URL);
const pallet = C.pallet(rpc, "System");
```

The return of `rpc` would be this wrapper type, and not actually initiate any connection until `open` is called.

Because the passing of the beacon to the factory is handled by the user, we would no longer have to propagate the `Beacon` generic everywhere.

**Comment by harrysolovay** [comment]
Done
