### ISSUE TITLE
ss58 decoded lengths

### ISSUE THREAD

**Issue by harrysolovay** [paritytech/capi#196]
@kratico pointed out [an interesting constant in the PolkadotJS util crypto source](https://github.com/polkadot-js/common/blob/1ac50696caefa39d77901bc85f0b9bc91e84bb26/packages/util-crypto/src/address/defaults.ts#L7). Does this suggest some behavior which is currently unaccounted for? Worth revisiting.

**Comment by tjjfvi** [comment]
We can get rid of this check; addresses can be invalid in a multitude of other ways, and so we'll just let it all error downstream.

**Comment by harrysolovay** [comment]
@kratico was this resolved by #751? If so, please close.
