### ISSUE TITLE
Simplify RPC Call Typings (for instance, `getBlockHash`)

### ISSUE THREAD

**Issue by karl-kallavus** [paritytech/capi#202]
Please implement `getBlockHash` utility to get the block hash for a specific block.

 e.g
`getBlockHash(blockNumber?: BlockNumber): BlockHash`

**Comment by harrysolovay** [comment]
I don't think we necessarily want to abstract over this RPC call (as it would not result in a reduction of complexity). You should be able to describe this with the following effect.

```ts
const result = await rpcCall(config, "chain_getBlockHash", []).read();
```

I suppose we could eliminate the need for the third arg by spreading...

```ts
const result = await rpcCall(config, "chain_getBlockHash").read();
```

... but then we get less desirable error positioning when args are supplied.

```ts
const result = await rpcCall(config, "some_method", arg_a, arg_b).read();
//                                                  ~~~~~~~~~~~~
//                                                  ^ pretend only arg_b is invalid –– highlights all of rest
```

Alternatively, we could accept props.

```ts
const result = await rpcCall({
  config,
  methodName: "chain_getBlockHash",
})
```

I've been thinking about this last approach––refactoring the RPC and certain effects to accept props––as it will simplify typings across the board. The union of RPC props can be discriminated by method name (as opposed to using a generic first argument to dynamically constrain the second argument (method-specific args)).

**Comment by harrysolovay** [comment]
No longer relevant
