### ISSUE TITLE
Expand Test Utils + Zombienet

### ISSUE THREAD

**Issue by harrysolovay** [paritytech/capi#215]
Let's model the Zombienet configuration (here is [the grammar's new/WIP AST](https://github.com/paritytech/zombienet/blob/4f0501c0f56b4d2fcfa41466257471b55a8bd519/crates/parser/src/ast.rs)) and integrate it into `test-util`.

cc @pepoviola

---

Ongoing list of test feature ideas:

- running dev-chain-spawning tests in parallel
- `collectExtrinsicEvents` (introduced in #211) –– perhaps with a slightly different interface.
- nice console messaging from test ctx / spawned Polkadot processes

**Comment by kratico** [comment]
For testing, it would be nice to specify a node configuration
For example, compiling the polkadot node with `cargo build --release --features fast-runtime`, creates a binary with shorter Launch/Voting/Enactment periods (see [polkadot](https://github.com/paritytech/polkadot/blob/2b0d83258089578b65712e143c794cf4922941de/runtime/polkadot/src/lib.rs#L590-L600) repo).

I'm not sure if it would be possible to get a new configuration with a runtime upgrade.

**Comment by pepoviola** [comment]
> For testing, it would be nice to specify a node configuration to speed up some operations.
> 
> For example, compiling the polkadot node with `cargo build --release --features fast-runtime`, creates a binary with shorter Launch/Voting/Enactment periods (see [polkadot](https://github.com/paritytech/polkadot/blob/2b0d83258089578b65712e143c794cf4922941de/runtime/polkadot/src/lib.rs#L590-L600) repo).
> 
> I'm not sure if it would be possible to get a new configuration with a runtime upgrade.

Using `fast-runtime` in our CI is part of this [pr](https://github.com/paritytech/polkadot/pull/5978/files#diff-037ea159eb0a7cb0ac23b851e66bee30fb838ee8d0d99fa331a1ba65283d37f7R220). That will produce an image (polkadot-debug) that we can use in zombienet with the fast-runtime.

**Comment by kratico** [comment]
Another thing to consider is launching polkadot nodes in parallel for testing.

Doing #211, the following was discovered
- `polkadot --dev --ws-port [port]` may not start to listen in the selected port if some other process is listening in that port and it will chose a different port.
  A workaround could be to make start a named polkadot node and make an rpc request to get the node name to validate that the node was started successfully in the specified port.
- killing a `Deno.Process` that started a polkadot non-detached docker container does not stop the container
  ```
  const p = Deno.run({cmd:["bash", "-c", "docker run --rm parity/polkadot:v0.9.25 --dev"]});
  p.kill("SIGKILL");
  p.close();
  ```
  A workaround could be to start the container detached with a name and use the container-id (or name) to be able to do `docker stop [id]`.

**Comment by tjjfvi** [comment]
Solved by the new dev server approach.
