### ISSUE TITLE
Utility for creating and interacting with an Escrow

### ISSUE THREAD

**Issue by jainkrati** [paritytech/capi#220]
### What is an Escrow:
Escrow is usually a multichain-tool utility (usually an account or a bridge) for performing a deal between two parties where any asset class (fungible tokens / non-fungible tokens ) from any chain can be deposited by one party or both and released / swapped with the other party when conditions of the deal are fulfilled. 

### Use cases for an escrow:
1. Swapping NFTs between two parties
2. Automatic conditional release of tokens deposited by one party to the other party as part of a deal. Example:Token vesting; Refunding payment when issue raised by consumer is proven to be genuine; 
3. Locking of an asset or pooling of assets
4. Multi-swap assets
5. Migrate assets from one parachain to other using a bridge based escrow (inspired by [this](https://github.com/paritytech/substrate-open-working-groups/blob/a0ba06276fc347f3b46e3a0c33e05977eb627100/SOWG/NFT-Migration-Protocol.md))

### Step Wise Escrow Creation:
**(following is some psuedocode)**
First of all let us import capi utilities:
```ts
import * as C from "../mod.ts";
```
Specify the kind of escrow we want to create:
1. Locker/Pooling Escrow
2. Swap Escrow
3. Conditional Release Escrow
4. Migration Escrow

Specify the asset to be locked / swapped / released and the time of the escrow operation.

```
const escrowAddress = await C.escrow.create({"<escrow_type>",[ <condition{asset_address, asset_quantity}> ], <locking_time>});
console.log(escrowAddress);
```

One or both parties can now deposit an asset and we print transaction id:
```
const depositTxId = await C.escrow.deposit(<assetAddress>);
console.log(depositTxId);
```

Once the deal is complete asset can be withdrawn :
```
const canWithdraw = await C.escrow.canWithdraw(<assetAddress>, <assetQuantity>);
if (canWithdraw) {
const withdrawTxId = await C.escrow.withdraw(<assetAddress>, <assetQuantity>);
console.log(depositTxId);
}
else {
console.log("Withdrawal not allowed");
}
```

##Reference links
[Escrow types](https://github.com/paritytech/contract-sizes/blob/a6bb3b0ee546fc116b6bc422c7716ddd0550bd2c/contracts/open-zeppelin/utils/README.adoc#escrow)
NFT Pooling inspired by [Polkaswap](https://polkaswap.medium.com/pooling-nft-on-polkaswap-2aa7727f61bb)
Escrow use cases inspired by [Polylokr](https://www.youtube.com/watch?v=QbI1Jkzztcw)

**Comment by harrysolovay** [comment]
TODO: dig into what utils may aid in interaction with the uniques pallet of Statemint

**Comment by tjjfvi** [comment]
We'll leave this to pattern lib devs.
