### ISSUE TITLE
Utility for creating a multisig wallet

### ISSUE THREAD

**Issue by jainkrati** [paritytech/capi#221]
### Step Wise Multi-Sig Creation:
One of the most common use cases of building on chain is to create a multi-signature account or multi-sig. For the uninitiated, a multi-sig is an account where shared between a number of people and each transaction requires a predecided minimum number of approval signatures. They are best suited for use cases where tokens are shared in single account between a number of people working together as an organisation. Let's see how we can create one using capi.

First of all let us import the modules from capi:
```ts
import * as C from "capi";
```

So capi has different modules for different purposes and in case of multi-signature wallet creation we need the MultiSig module.

It creates a multi-sig wallet from three parameters:
1. The primary signer address for signing the multi-sig wallet creation transaction
2. The list of secondary signer addresses, which will be part of the multi-sig apart from primary signer
3. The threshold which signifies minimum number of approvals needed to perform a transaction using this multi-sig account

So let's create constants for each of these because they are not going to change during our program scope.
```ts
declare const PRIMARY: Uint8Array;
declare const SECONDARY: Uint8Array[];
declare const THRESHOLD: number;
```

Next let's invoke the call for creating the multi-sig with these 3 parameters
```ts
const xMultiSig = C.MultiSig.from(
  PRIMARY,
  SECONDARY,
  THRESHOLD
);
```

Next we need the signer wallet to sign the transaction and send it to the chain for processing. 

```ts
const xPending = xMultiSig.pending.get(proposalId);
const approvalTx = xPending.sign(signer)
```

Once the processed, the transaction is finalised we will receive the address of the newly created multi signature wallet account.
```ts
const multiSigAddress = await approvalTx.send();
```

Congratulations on creating the multi-sig wallet using capi !!!

### Additional utility:
Based on the most configs for multi-sig wallets we can extract out the wallet creation processes in a new utility inside the MultiSig module of capi as follows:
```ts
const xMultiSig = await C.MultiSig.with(
  PRIMARY,
  SECONDARY,
  THRESHOLD,
  proposalId,
  signer
);
```
This utility takes care of abstracting away different operations in a single call for the developer. Under the hood every thing is same.

**Comment by harrysolovay** [comment]
Offline discussion with @jainkrati:

```ts
import * as polkadot from "./polkadot.ts";
import * as C from "capi";

declare const PRIMARY: Uint8Array;
declare const SECONDARY: Uint8Array[];
declare const THRESHOLD: number;

// perhaps a `C.MultiSig.ensure` method incase wallet does not exist
const xMultiSig = C.MultiSig.from(
  PRIMARY,
  SECONDARY,
  THRESHOLD,
  // ... misc. config (withdrawal limit?)
);

const xPending = xMultiSig.pending.get(proposalId);

const approvalTx = xPending.sign(signer)

await approvalTx.send();
```

- what other configuration do we want to enable?
- signer designation
- flow for a specific signer / rejection
- TODO(@jainkrati): scope out the range of configuration options

**Comment by kratico** [comment]
Leaving some findings
- there are 2 types of multisig approvals
  - non-executing approval, needs a callHash (this is for voting)
  - executing approval, needs a callData (this is required for first and final approval)

Useful recipes/APIs
- create a multisig address [recipe](https://github.com/polkadot-js/common/blob/3597a4eb4e0cf9985104568058c5cd23701bbaed/packages/util-crypto/src/address/keyMulti.ts#L15-L23)
- multisig address configuration (signatories and threshold), ???
- extrinsic `multisig.asMulti(otherSignatories, threshold, callData, timepoint?, ...)`, needed for initial/executing approval, notices that `callData` is needed to execute the approval
- extrinsic `multisig.approveAsMulti(otherSignatories, threshold, callHash, timepoint?, ...)`, will vote but not execute, notice that `callHash` is used
- extrinsic `multisig.cancelAsMulti(threshold, otherSignatories, timepoint, callHash)`
- storage `multisig.multisigs(multisigAddress, callHash)`, returns approvers and initial approval timepoint for a pending proposal

Notice that for all the above extrinsics, the multisig address configuration is needed.

**Comment by harrysolovay** [comment]
Still fine-tuning this API, but it's relatively clean as of #454.
