### ISSUE TITLE
Preflight RPC `methods` Check

### ISSUE THREAD

**Issue by harrysolovay** [paritytech/capi#231]
We type the constraint of effect configs with the required-to-be-accessible RPC methods, but we do not verify at runtime that these methods are accessible; we assume they are. How to proceed?

**Comment by kratico** [comment]
I think this is similar to types, it could be static or dynamic.
If it's dynamic it should be cached.

Then it can be injected in several places, for example
- it could be cached in the zone runtime context
- or, it could be injected as an argument to the `rpcCall`/`rpcSubscription` atoms
- or, it could be injected in `rpcClient` 

Injecting it through the runtime context could give the flexibility to do the check anywhere.

**Comment by tjjfvi** [comment]
If we use a method that doesn't exist, it will error. And we'll be using `state_call` soon enough.
