### ISSUE TITLE
Capture NFT Pattern Library

### ISSUE THREAD

**Issue by jainkrati** [paritytech/capi#242]
A continuations of https://github.com/paritytech/capi/issues/222
This is a work in progress

### Use cases of the NFT Pattern Library:

Along with some **psuedocode**
1. Create conditionally owned NFTs : Example includes booster NFTs in a game, priviledge NFTs above a particular score in a test
```ts
import * as C from "../mod.ts";
const xNFTAddress = await C.nft.create({"conditional", ownershipEvaluatorFunction});
console.log(xNFTAddress);
```
2. Create fractionally owned NFTs : Examples include an event NFT owned fractionally by all attendees, Photo NFT owned by everyone who was in the photo
```ts
const xNFTAddress = await C.nft.create({"fractional"});
```
3. Create rentable NFTs / subscription based NFTs : Examples include metaverse land lease / renting power-ups/add-on in a game 
```ts
const xNFTAddress = await C.nft.create({"rentable", rent});
```
4. Create generative NFTs : These are NFTs that change asset/attributes as time or ownership changes
```ts
const xNFTAddress = await C.nft.create({"generative", generativeAssetID});
```
5. Create on-chain NFTs: These NFTs store all the assets (like image/text/audio) on chain; examples include Proof Of Attendance Picture (POAP) , Appreciation/Kudos NFTs, Gift Voucher NFTs where owner's name and other details are the on chain content in the NFT
```ts
const xNFTAddress = await C.nft.create({"onChain", dynamicSVG});
```
6. Mint and Transfer NFTs
```ts
await C.nft.mint(xNFTAddress, ownerAddress);
```
7. Get NFT attribute : Useful for token gating access on basis of attribute value
```ts
await C.nft.get(attributeName);
```
8. Get all token holders
```ts
await C.nft.getHolders(xNFTAddress);
```

### So how does it work behind the scenes?
We can either use an existing library like rmrk or we can create NFT constructs from scratch. This is open for discussion. 

##Reference links
1. https://www.rmrk.app/
2. https://enjin.io/blog/efinity
3. https://unique.network/
4. https://unqnft.io/

**Comment by harrysolovay** [comment]
Will leave this as a TODO for pattern lib development (not to be in Capi's core)
