### ISSUE TITLE
Enable low level function calls for different chains.

### ISSUE THREAD

**Issue by jainkrati** [paritytech/capi#271]
As of today developers find it difficult to interact with polkadot/api for low level calls like asset transfers between two accounts on different chains. If capi could create simple declarative wrapping functions over each/most low level apis then DX will drastically improve; even for new devs.

Attaching screenshot of a questions asked (about asset transfer and balance queries) in polkadot channel which supports this use case:

<img width="864" alt="Screenshot 2022-09-30 at 2 00 49 PM" src="https://user-images.githubusercontent.com/7895856/193752010-c2666de0-4120-43c4-a254-0a5f2a12e049.png">

<img width="843" alt="Screenshot 2022-09-28 at 7 50 37 PM" src="https://user-images.githubusercontent.com/7895856/193573880-19fe9bd6-9689-435d-8a7e-f2d1f039a801.png">

<img width="867" alt="Screenshot 2022-09-28 at 7 51 59 PM" src="https://user-images.githubusercontent.com/7895856/193574253-9205f4e8-0055-42fd-89c5-48983a46c2d5.png">

**Comment by harrysolovay** [comment]
@jainkrati can you please elaborate on the problem? Not exactly sure what's meant by "low-level interactions" or why `@polkadot/api` would not service these interactions.

**Comment by jainkrati** [comment]
In scenarios where developer has launched their own tokens/assets on the parachain and want to transfer these tokens from account1 to account2 (as seen in the screenshots above), developers can benefit if Capi provides a utility to transfer these user created assets. The complexity of doing so using polkadot or cumulus can be abstracted out.

**Comment by harrysolovay** [comment]
Ah, okay. What are the "low-level interactions" of which this pattern would be composed? Seems Westmint's `assets` pallet's `transfer` should do the trick? What's missing?

**Comment by jainkrati** [comment]
Yes, it should do the trick. I guess I wrongly used "low-level" interactions. I meant "basic asset" interactions

**Comment by harrysolovay** [comment]
Gotcha. In that case, this should be covered. Not sure if we need this issue to represent any corresponding work. Want to mark this as closed?

**Comment by jainkrati** [comment]
Closing the issue.
