### ISSUE TITLE
Support for storing and retrieving data off-chain and on-chain.

### ISSUE THREAD

**Issue by jainkrati** [paritytech/capi#274]
Different parachains may be dependent on data external to polkadot. Example: A fantasy football app rewards users depending on the real scores during a football match. Every user locks in their estimate of total score of each team on the parachain in the form of an on-chain bid. The rewarding mechanism needs live scores of the game while it transfers tokens to the winning bidders.

If Capi could support interacting with a football score transmitting extrinsic/oracles, then it would be wonderful and handy for the devs to code this dApp.

```ts
import * as C from "capi";

// NOTE: psuedo code as SomeOraclePallet / SomeOracleEntry is yet to be finalized 
const retrievedData = await C.readEntry(
  C.config("wss://some.chain.io", 0),
  "SomeExtrinsicPallet",
  "SomeExtrinsicEntry",
   dataId);
).read();

let winningBid = chooseWinningBid(bids, retrievedData.teamOneScore, retrievedData.teamTwoScore)
```

**Comment by harrysolovay** [comment]
Outside of Capi's scope––would require some on-chain program specifics + oracle interaction.
