### ISSUE TITLE
Some Initial Use Cases

### ISSUE THREAD

**Issue by jainkrati** [paritytech/capi#275]
Couple of use cases:

1. Enable staking assets
Many Defi and Gaming applications built on Polkadot would have launch own tokens. As part of the product feature, there is a high possibility that these dApps would want to users to lock-in or even stake these tokens (could be fungible, non-fungible or semi-fungible) tokens. 

How amazing it would be if capi could enable staking custom tokens for any product (built on any parachain) and allow user to earn a % :
`capi.stake(tokenA_address, token_amount, lock_in_duration, staking_percent)`

2. Enable transaction simulation / preflight to let developers know the results.
There are complex situations where it would really help to simulate a transaction before executing on the main network. This gives developers the freedom and information about handling edge cases
`
let tx = transferOwnership(nftA, userB_address)
await capi.simulate(tx)
`

3. Enable DAO functions on chain including treasury management
There are many functions in a DAO which happen on-chain like voting, grants, governer selection. If capi could enable 
these, it would act like a utility for building DAO Tools:
`
let voteAddress = capi.createVote(voteTitle, voteDescription, votingOptions, voteDeadline, votingType = VotingType.Qudratic);
// Evaluate winner
let winningOption = capi.evaluateWinner(voteAddress);
// Give grant to winner
let escrow = capi.createEscrow(winningOption.granteeAddress, winningOption.title, winningOption.grantAmount)
capi.transferFunds(escrow)
`

4. Enable communicating with bridges
Many deFi / gaming apps could benefit from asset transfers and exchanging information from other parachains using bridges. XCM could also be used to solve this use case. CAPI could abstract out the implementation and provide a utility like:
`
// Defi app running on Acala listens to confirmation of trees planted, from renewable energy based parachain, say TREES and unlocks some carbon credits in handlerFunction
capi.listenXCEvent(trees_chain, EventType.TreesPlanted, minAmountOfTrees, handlerFunction)
`
5. Off-ramp and on-ramp utility to convert fiat to crypto and vice-versa
For wallets built on top of polkadot, capi could provide a utility to deposit fiat and convert them to an asset of users choice. This utility works off chain as well as on chain:
`
let tx = await capi.onRamp(FiatCurrencyType.USD, fiat_amount, token_address, user_wallet_address )
`
Vice-versa:
`
let tx = await capi.offRamp(token_address, token_amount, FiatCurrencyType.USD)
`

**Comment by tjjfvi** [comment]
We'll leave this to pattern lib devs.
