### ISSUE TITLE
Get Rid of Inaccurate "Used By"

### ISSUE THREAD

**Issue by harrysolovay** [paritytech/capi#279]
We were previously generating some wasm+bindings, the Rust root crate of which was named `mod`. The repo's "used by" section (incorrectly) picked up on this and reflected the following.

<img width="162" alt="Screen Shot 2022-10-04 at 9 42 40 PM" src="https://user-images.githubusercontent.com/4893548/193850069-1d9395ce-cc2c-4aec-8075-6719541df27c.png">

Hasn't disappeared, even since removing the Rust code.

**Comment by tjjfvi** [comment]
We probably need to take this up with GH support if we want to get this resolved

**Comment by harrysolovay** [comment]
Support resolved this within 1 hour of submitting the request.

> Thank you for contacting GitHub support. I have removed the used by section of your repository and reassigned the crate so the dependents no longer show in the Dependency Graph either. Both of these are actions only GitHub support is able to perform, so they are not something you would have been able to do.

Well done GitHub.
