### ISSUE TITLE
Dependabot is Dependably Aggravating

### ISSUE THREAD

**Issue by harrysolovay** [paritytech/capi#290]
What can be done? @sergejparity, any recommendations?

**Comment by harrysolovay** [comment]
<img width="759" alt="Screen Shot 2022-10-12 at 4 55 18 PM" src="https://user-images.githubusercontent.com/4893548/195446086-02fcb41d-f0c8-4a40-af12-3fccd0b00a20.png">

I should note, its PRs require admin merge.

**Comment by sergejparity** [comment]
@harrysolovay was the problem with the PR's created by @dependabot like this one https://github.com/paritytech/capi/pull/287? (can't find any problems with that)

Or with created by GHA https://github.com/paritytech/capi/blob/82308eb581ee74f0a7a42e746f7755dd71cc230a/.github/workflows/udd.yml#L25-L35 ?
This one produces unverified commits as I can see from here https://github.com/paritytech/capi/pull/292/commits

**Comment by harrysolovay** [comment]
@sergejparity you're correct. Just updated my last comment:

> these PRs are from UDD, not dependabot. Ie., unrelated.

Nothing to be done for now––still, going to leave this issue open (hoping to eventually simplify dependency updates).
