### ISSUE TITLE
ESM packages (./worker.js) need to be imported

### ISSUE THREAD

**Issue by karl-kallavus** [paritytech/capi#295]
## Bug Report

Issue happens in Next.js environment 

```
../node_modules/capi/node_modules/@substrate/smoldot-light/dist/worker/spawn.js
Module not found: ESM packages (./worker.js) need to be imported. Use 'import' to reference the package instead. https://nextjs.org/docs/messages/import-esm-externals
```

There's a workaround if you enable 
`experimental: { esmExternals: 'loose' }`

Regarding to @harrysolovay it does appear to be a smoldot issue, but perhaps because Capi does a dynamic import of Smoldot, which some environments dislike.

**Comment by tjjfvi** [comment]
Lots has changed; no longer an issue.
