### ISSUE TITLE
Implement EntriesWatch to subscribe to multiple storage entries

### ISSUE THREAD

**Issue by kratico** [paritytech/capi#336]
Add a `C.EntriesWatch` (or similar) that works similar to https://github.com/paritytech/polkadot-staking-dashboard/blob/a9df069f1968c7540ec75b17d5a6a3200c8a6cd9/src/contexts/Staking/index.tsx#L205

**Comment by kratico** [comment]
cc @rossbulat

**Comment by harrysolovay** [comment]
We've more-or-less implemented this via `Rune.rec` and `Rune.tuple` in conjunction with the `iter` method (which may soon be reverted back to its old name of `watch`).

```ts
import { Rune } from "capi"
import { chain, Timestamp } from "polkadot/mod.ts"

const block = chain.latestBlock
const extrinsics = block.extrinsics()
const events = block.events()
const now = Timestamp.Now.entry([], block.hash)

const root = Rune.rec({
  hash: block.hash,
  block,
  extrinsics,
  events,
  now,
})

let i = 0
for await (const values of root.iter()) {
  console.log(values)
  if (++i === 3) break
}
```
