### ISSUE TITLE
`MultiAddress` Utils

### ISSUE THREAD

**Issue by harrysolovay** [paritytech/capi#348]
To be used within the formation of extrinsics ([see here](https://github.com/paritytech/capi/blob/863eec5ed15da1ae57390bd73175348aa15c5270/effects/extrinsic.ts#L58-L73))

**Comment by harrysolovay** [comment]
Any wisdom [here](https://github.com/airgap-it/airgap-coin-lib/blob/44a9acec71418c9f1bb253a9189e8833e2657317/packages/core/src/protocols/substrate/common/data/scale/type/SCALEMultiAddress.ts)?

**Comment by tjjfvi** [comment]
Closing in favor of #619
