### ISSUE TITLE
multisig - option to configure multiple tiers (sets of rules) based on value of transaction

### ISSUE THREAD

**Issue by danielpetroff** [paritytech/capi#397]
### Suggestion

An option when setting up the Multisig to allow the user to configure multiple sets of rules depending on value of transaction.

### Motivation

This is something often used to control who can approve transactions of what maximum size.

### Use Cases
<--UC1-->
3 - Tier approval structure, anybody can initiate a transaction

Can initiate any transaction: Tier 1, 2, and 3
Can approve transactions up to $10k: Tier 1, 2, and 3
Can approve transactions up to $100k Tier 2 and 3
Can approve transactions over $100k: Tier 3
</--UC1-->

<--UC2-->
3 - Tier approval structure, can only initiate a transaction of a particular tier or lower and approve same tier or lower

Can initiate and approve transactions up to $10k: Tier 1, 2, and 3
Can initiate and approve transactions up to $100K: Tier 2 and 3
Can initiate and approve transactions over $100k: Tier 3
</--UC2-->

**Comment by danielpetroff** [comment]
I do not know if Substrate supports this yet.

**Comment by harrysolovay** [comment]
> This seem more like a feature request for the multisig pallet on substrate, not capi

Agreed. That being said, this does sound like a compelling use case. Let's take note of this use case and follow up in the form of Capi + a smart contract (once we've properly addressed smart contract interactions).
