### ISSUE TITLE
Add utility to get list of signatories of a multisig

### ISSUE THREAD

**Issue by jainkrati** [paritytech/capi#404]
For sub0 demo, we need to show all signatories (addresses) of a multisig. So we need a utility in capi for same.
`
const signatories = capi.signatoriesFromMulti("<multisig_address_here>")
`

**Comment by kratico** [comment]
This would be out of scope for Capi.
As far as I know the multisig address signatories and threshold are not stored on chain.
As an alternative, I would suggest to have each signatory to add the multisig address to their own address book (similar to polkadot js)
