### ISSUE TITLE
show docs in codegen server pallet path completions

### ISSUE THREAD

**Issue by harrysolovay** [paritytech/capi#460]
Unfortunately, FRAME Metadata does not currently expose pallet-specific documentation (see paritytech/frame-metadata#47).

As an experiment, I attempted to simply fetch from the pallet-name-corresponding Readme of the paritytech/substrate repo. This is of course not a viable solution, as it doesn't account for version nor differences between chain-specific pallets / pallets with the same names as those in FRAME.

Is there a good way of determining pallet documentation source? If so, I believe the experience is merited.

<img width="1087" alt="Screen Shot 2022-12-11 at 1 57 22 PM" src="https://user-images.githubusercontent.com/4893548/206923266-fa3a88c1-4097-40f7-af41-1ecba54ff591.png">

**Comment by tjjfvi** [comment]
No longer relevant as we don't have completions anymore
