### ISSUE TITLE
how should major releases of polkadot affect semantic capi releases?

### ISSUE THREAD

**Issue by ryanleecode** [paritytech/capi#476]
Currently we target [polkadot version 0.9.31](https://github.com/paritytech/capi/blob/86ffa2b9954a239d096994e2a9bcbdc650dc2a0a/examples/multisig_transfer.ts#L5) with the expectation that capi will always support the latest release of polkadot. What is the impact of upgrading polkadot in Capi wrt to semantic releases.

For example if I as a user am using Capi 1.0.0 and we are targeting polkadot 0.9.31, and we upgrade polkadot to 0.10, would this trigger a major release of Capi since users on the 1.x.x semantic release have "locked in" polkadot version 0.9.x?

**Comment by tjjfvi** [comment]
Capi tries to be as chain-independent as possible. Right now our *tests* are pinned to polkadot version 0.9.31, but there's no reason that capi itself can't be used with polkadot 0.9.36, or 0.9.30.

**Comment by tjjfvi** [comment]
The main reason we pin our tests is that we snapshot various things like metadata etc. and we don't want that changing arbitrarily when capi devs happen to install new versions of polkadot.

**Comment by ryanleecode** [comment]
right makes sense we don't have a dependency on polkadot anywhere except the example/test code.
