### ISSUE TITLE
make dprint config more deterministic

### ISSUE THREAD

**Issue by harrysolovay** [paritytech/capi#488]

**Comment by tjjfvi** [comment]
Elaborate?

**Comment by harrysolovay** [comment]
One example is the following:

```ts
const x = fn(
  arg0,
);
```

I believe it would be ideal for this to format in a consistent manner, regardless of the line break after `fn`. Aka, it should always format to the following.

```ts
const x = fn(arg0);
```

In cases where the resulting line width is greater than the configured 100 chars, it would wrap.

There are other cases like this in which less-meaningful input (such as whitespace) has bearing on the formatting.

Thoughts?

**Comment by tjjfvi** [comment]
I think this is neither possible (with dprint) nor desirable.

Though *largely* deterministic automatic formatting is good as it lifts the mental burden of manually formatting code, *some* control of formatting is still desirable, as it in some cases allows one to make one code more readable. Even prettier – which aims for completely deterministic formatting – has non-deterministic formatting regarding line breaks.

Ultimately, the best balance is – IMO – a code formatting tool that gives you a very limited set of options for formatting. This means that one still has some control, and can format it in a way that feels natural and readable, but the space one has to consider is narrowed from [all possible ways the code could be formatted with whitespace] to [should this be multiline?].

This also makes the configured max of 100 chars much saner, as it means that lines are only 100 chars long if a human has decided not to wrap it. There are many many things that *could* be one 100-char line, but is much more readable split across multiple lines. By the same token, there are many things that are perfectly readable as one long line. It's best to rely on human judgement for this, at least until we have FormatGPT ;)

**Comment by harrysolovay** [comment]
I agree: there are plenty of cases in which a human must decide what is the most sane formatting. Still...

> the mental burden of manually formatting code

I'm still feeling this burden in more cases than just that which I noted above. It's not too costly... let's table this for now. **At the very least, I'm sure we could refine our Dprint config and then use it in other projects that we administrate.**
