### ISSUE TITLE
`U.isChainSpec`

### ISSUE THREAD

**Issue by harrysolovay** [paritytech/capi#493]
#487 is in need of a guard to determine whether something is a chainspec (and perhaps what kind as well).

Given that smoldot accepts the JSON string, it would be nice to avoid the intermediate `JSON.parse`. Not sure how best to tackle this. Maybe the (aside-from-validation) useless parse is unavoidable.

```ts
import { isChainSpec } from "../util/chainSpec.ts"

declare const chainSpec: string

const chainSpecParsed = JSON.parse(chainSpec)

if (isChainSpec(chainSpecParsed)) {
  // ...
}
```

Thoughts @kratico?

**Comment by tjjfvi** [comment]
Smoldot itself validates this; no need for us to.
