### ISSUE TITLE
500 Error in Mutlisig test during CI

### ISSUE THREAD

**Issue by ryanleecode** [paritytech/capi#508]
## Bug Report
Builds randomly fail with 500 error in mutlisig example. Needs investigation.

https://github.com/paritytech/capi/actions/runs/3975358001/jobs/6815177284

**Comment by harrysolovay** [comment]
Might this be fixed by updating the Deno version as specified throughout the repo?

**Comment by ryanleecode** [comment]
> Might this be fixed by updating the Deno version as specified throughout the repo?

where does it reference deno version? I see

```
error: error sending request for url (http://localhost:5646/@local/proxy/dev:polkadot/@v0.9.36/mod.ts): error trying to connect: tcp connect error: Connection refused (os error 111)
    at file:///home/runner/work/capi/capi/examples/multisig_transfer.ts:6:27
```

**Comment by harrysolovay** [comment]
Ah, I was seeing some 500s for anything requested from denoland/x in other runs. This seems unrelated. Nvrmind.

**Comment by ryanleecode** [comment]
Has to do with multisig transfer being excluded from `mod.ts` in examples after running `moderate` task.

**Comment by harrysolovay** [comment]
This is what I was talking about: https://github.com/paritytech/capi/actions/runs/3988979948/jobs/6840844754#step:8:405

<img width="827" alt="Screen Shot 2023-01-23 at 12 34 48 PM" src="https://user-images.githubusercontent.com/4893548/214109557-1eb1ca49-f3d1-4918-b906-66dbb678befc.png">

**Comment by harrysolovay** [comment]
No longer seems to be an issue. Will reopen if this error crops up again in the future.
