### ISSUE TITLE
add multisig proxy example

### ISSUE THREAD

**Issue by ryanleecode** [paritytech/capi#525]
Add an example that utilizes a mutlisig behind a proxy. the example should be able to change who can access the proxy and thus also access the mutlisg.

**Comment by tamrai** [comment]
Hi @ryanleecode! We are trying to model the multisig/proxy flow using CAPI. Would be great to get some help on it!

## Diagram

![c](https://user-images.githubusercontent.com/7630720/216309354-ef39ed1b-230b-40d3-9e78-749828650e90.png)

## Pseudo code

```js
// 1. Create pure proxies by Alice
const stashProxy = await ALICE.proxy.createPure().signAndSend()
const aliceProxy = await ALICE.proxy.createPure().signAndSend()
const bobProxy = await ALICE.proxy.createPure().signAndSend()
const charlieProxy = await ALICE.proxy.createPure().signAndSend()

// 2. Get multisig address
const MULTISIG = Rune
  .resolve({
    signatories: [aliceProxy, bobProxy, charlieProxy],
    threshold: 2,
  })
  .as(MultisigRune, client) 

// 3. Top up proxies and multisig
await Balances
  .transfer({
    value: 2_000_000_000_000n,
    dest: MultiAddress.Id(MULTISIG.address),
  })
  .signed({ sender: ALICE })
  .sent()
  .logStatus("Existential deposit:")
  .finalized()
  .run()

await Balances
  .transfer({
    value: 2_000_000_000_000n,
    dest: stashProxy,
  })
  .signed({ sender: ALICE })
  .sent()
  .logStatus("Existential deposit:")
  .finalized()
  .run()
// ... repeat for: aliceProxy, bobProxy, charlieProxy

// 4. Set up proxies according to the diagram
await ALICE.proxy(stashProxy).addProxy(MULTISIG).signAndSend()
await ALICE.proxy(bobProxy).addProxy(BOB).signAndSend()
await ALICE.proxy(charlieProxy).addProxy(CHARLIE).signAndSend()

await ALICE.proxy(stashProxy).removeProxy(ALICE).signAndSend()
await ALICE.proxy(bobProxy).removeProxy(ALICE).signAndSend()
await ALICE.proxy(charlieProxy).removeProxy(ALICE).signAndSend()

// 5. Perform voting
// The to-be proposed and approved call
const sendFundsToDaveFromStashProxy = MULTISIG.proxy(stashProxy).extrinsic(
  Balances.transferKeepAlive({
    dest: DAVE.address,
    value: 1_230_000_000_000n,
  })
)

// Submit a proposal to dispatch the call
await MULTISIG
  .ratify({ call: sendFundsToDaveFromStashProxy, sender: ALICE.proxy(aliceProxy) })
  .signed({ sender: ALICE })
  .sent()
  .logStatus("Proposal:")
  .finalized()
  .run()

// Send the approve and execute if final approval
await MULTISIG
  .ratify({ call: sendFundsToDaveFromStashProxy, sender: CHARLIE.proxy(charlieProxy) })
  .signed({ sender: CHARLIE })
  .sent()
  .logStatus("Approval:")
  .finalized()
  .run()

// Dave received funds from STASH
console.log("Dave final balance:", await System.Account.entry([DAVE.publicKey]).run()) // await getBalance(DAVE) ?
```

## Extrinsics

- [`proxy createPure(proxyType, delay, index)`](https://polkadot.js.org/docs/substrate/extrinsics#createpureproxy_type-kitchensinkruntimeproxytype-delay-u32-index-u16)
- [`addProxy(delegate: MultiAddress, proxy_type: KitchensinkRuntimeProxyType, delay: u32)`](https://polkadot.js.org/docs/substrate/extrinsics#createpureproxy_type-kitchensinkruntimeproxytype-delay-u32-index-u16)
- [`removeProxy(delegate: MultiAddress, proxy_type: KitchensinkRuntimeProxyType, delay: u32)`](https://polkadot.js.org/docs/substrate/extrinsics#removeproxydelegate-multiaddress-proxy_type-kitchensinkruntimeproxytype-delay-u32)
- [`proxy(real: MultiAddress, force_proxy_type: Option<KitchensinkRuntimeProxyType>, call: Call)`](https://polkadot.js.org/docs/substrate/extrinsics#proxyreal-multiaddress-force_proxy_type-optionkitchensinkruntimeproxytype-call-call)
- [`asMulti(threshold: u16, other_signatories: Vec<AccountId32>, maybe_timepoint: Option<PalletMultisigTimepoint>, call: Call, max_weight: SpWeightsWeightV2Weight)`](https://polkadot.js.org/docs/substrate/extrinsics#asmultithreshold-u16-other_signatories-vecaccountid32-maybe_timepoint-optionpalletmultisigtimepoint-call-call-max_weight-spweightsweightv2weight)
- [`cancelAsMulti(threshold: u16, other_signatories: Vec<AccountId32>, timepoint: PalletMultisigTimepoint, call_hash: [u8;32])`](https://polkadot.js.org/docs/substrate/extrinsics#cancelasmultithreshold-u16-other_signatories-vecaccountid32-timepoint-palletmultisigtimepoint-call_hash-u832)
- [`approveAsMulti(threshold: u16, other_signatories: Vec<AccountId32>, maybe_timepoint: Option<PalletMultisigTimepoint>, call_hash: [u8;32], max_weight: SpWeightsWeightV2Weight)`](https://polkadot.js.org/docs/substrate/extrinsics#cancelasmultithreshold-u16-other_signatories-vecaccountid32-timepoint-palletmultisigtimepoint-call_hash-u832)
- [`transferKeepAlive(id: Compact<u32>, target: MultiAddress, amount: Compact<u128>)`](https://polkadot.js.org/docs/substrate/extrinsics#transferkeepaliveid-compactu32-target-multiaddress-amount-compactu128)

## Polkadot.js app (visualisation)

![a](https://user-images.githubusercontent.com/7630720/216310249-29b33737-d2c1-4c9b-adf8-238bb0dc9dcd.png)

**Comment by karl-kallavus** [comment]
I'll try to describe the flow we're trying to achieve with API. 

Alice wants to configure the future multisig by adding Bob and Charlie as signatories with proxies and setting a signatory threshold. 

Alice wants to create Pure Proxy that will become the "stash" in the multisig setup and attach the multisig setup to the stash.

(check the Diagram above)

In that case Alice has to create 4 pure proxies: `AlicePureProxy`, `BobPureProxy`, `CharliePureProxy` and `StashPureProxy`

It will be good it we introduce batch transaction to reduce the amount of Alice's signs.

First Alice construct a list of transactions to batch

```
const proxies = [
  proxy.createPure(type), // pure proxy for Alice
  proxy.createPure(type), // for Bob
  proxy.createPure(type), // for Charlie
  proxy.createPure(type), // for Multisig
];
```

const participants = Rune.array([alice, bob, charlie, stash])

const proxies = 

```

const initialParticipants = ['alice', 'bob, 'charlie', 'stash'];

await Utility.batchAll({
  calls: initialParticipants.map((participant) =>
    Proxy.createPure({
      proxyType: "any",
    })
  ),
})
  .signed({ sender: alice })
  .sent()
  .logStatus()
  .finalized()
  .unwrapError()
  .run()
```

```
await Proxy
  .createPure([
    {type: 'any'},
    {type: 'any'},
    {type: 'any'},
    {type: 'any'},
  ])
  .signed({ sender: alice })
  .sent()
  .logStatus("Creating pure proxies:")
  .finalized()
  .run()
```



First Alice creates PureProxies for 



Also 

First thing first Alice creates

**Comment by Goranch3** [comment]
@karl-kallavus is it possible to send funds to all pure-proxy accounts and multisig all at once, like on the diagram below?
![Frame 3399](https://user-images.githubusercontent.com/92366349/216590233-c1548eff-84e6-47ac-9432-b632e505935a.png)

**Comment by tamrai** [comment]
Great! I wanted to keep it simple at the beginning, but batch transactions are definitely something desired especially from the UX perspective! @Goranch3 Yes. We can send same [existential deposits](https://wiki.polkadot.network/docs/build-protocol-info#existential-deposit) to proxies and maybe a more configured deposit for the Stash (bank).

**Comment by ryanleecode** [comment]
Initializing pure proxies will automatically fund them. It is otherwise impossible to send funds to a proxy.

**Comment by statictype** [comment]
@ryanleecode not sure this is true.
a deposit is reserved when creating the pure proxy. at the moment, the reserved balance contributes to the ED but with the upcoming changes in Substrate reserved balance will no longer keep the account alive. it will need to have a minimum free balance. https://github.com/paritytech/substrate/pull/12951

a pureProxy address should behave the same way as any other address, meaning if you send funds to it after it was reaped it should be restored on-chain

**Comment by ryanleecode** [comment]
> @ryanleecode not sure this is true. a deposit is reserved when creating the pure proxy. at the moment, the reserved balance contributes to the ED but with the upcoming changes in Substrate reserved balance will no longer keep the account alive. it will need to have a minimum free balance. [paritytech/substrate#12951](https://github.com/paritytech/substrate/pull/12951)
> 
> a pureProxy address should behave the same way as any other address, meaning if you send funds to it after it was reaped it should be restored on-chain

yeah forget what i said. just a bug on myside :smile:

**Comment by ryanleecode** [comment]
What is the point of `approveAsMulti` it seems completely useless and doesnt do anything

**Comment by tjjfvi** [comment]
IIRC `approveAsMulti` allows you to approve by sending just the call hash, not the full call, which is less expensive. You only need to send the full call on the last approval.
