### ISSUE TITLE
handling multiple instances of same pallet

### ISSUE THREAD

**Issue by harrysolovay** [paritytech/capi#551]
PJS has the following

```ts
const instances = api.registry.getModuleInstances(specName, 'electionsPhragmen') || [];
```

How might we want to address the same concern?

**Comment by tjjfvi** [comment]
I suspect this only occurs when you have multiple chains in the same PJS registry. If not, can you give an example where the same pallet occurs multiple times on a singular chain?

**Comment by harrysolovay** [comment]
@kianenigma –– any thoughts on this?

**Comment by kianenigma** [comment]
> have multiple chains in the same PJS registry

No -- You can have multiple instances of the same pallet at the same runtime.

**Comment by kianenigma** [comment]
Somewhere in the metadata, for each pallet, you should have the "pallet name" (pallet-collective), and somewhere else the "instance name" (council): 

https://github.com/paritytech/polkadot/blob/master/runtime/polkadot/src/lib.rs#L1507

**Comment by tjjfvi** [comment]
Looks like we already use the instance name and not the pallet name in our consumption of the metadata, so this should be fine. I presume it's safe to assume the instance names are unique for the chain?
