### ISSUE TITLE
integrating with the zombienet programmatic CLI

### ISSUE THREAD

**Issue by harrysolovay** [paritytech/capi#561]
Currently, we make use of Zombienet via its CLI + [manual retyping of `Network`](https://github.com/paritytech/capi/blob/dfcaf3b677b4bc6eb0940efddd488f0ce92f6279/deps/zombienet/orchestrator.ts). At some point soon, we'll want to integrate with the Zombienet programatic API, as well as make use of its types directly. My understanding is that this will require a few more changes relating to Deno compatibility. Let's make sure to track this progress (paritytech/zombienet#259). Tagging @pepoviola for good measure.

**Comment by pepoviola** [comment]
Hi @kratico ping me if you have time this week to touch base on this.
Thanks!

**Comment by tjjfvi** [comment]
Done in #641
