### ISSUE TITLE
redundancy in codegen typing

### ISSUE THREAD

**Issue by harrysolovay** [paritytech/capi#562]
Let's say we're utilizing a codegened `client`.

```ts
import { client } from "polkadot_dev/mod.ts"
```

We can get the strongly-typed events.

```ts
;(await client.latestBlock
  .events()
  .run()).forEach((event) => {
    event.event.type // narrow / string-literals of pallet names
  })
```

However, other bindings of `client` are untyped. For instance, we can bind to non-existent pallet names.

```ts
const result = await client
  .metadata()
  .pallet("J Cole is a great rapper")
  .run()
```

Granted, we want devs to make use of the generated pallet bindings, which safely wrap pallet access... still, unless we're going to hide the `pallet` method from the generated client, this feels inconsistent.

Unless the checker performance cost is too high, I propose that we do both (chain-specific types passed through client-rooted API + explicitly re-typed bindings that wrap common access points).

**Comment by harrysolovay** [comment]
I believe it will be important to pass a comprehensive chain type through the fluent API. This just became clear, as I attempted to create two overloads for the `block.events` method, which would enable devs to optionally specify event pallet and name when retrieving block events.

```diff
const result = await Balances
  .transfer({
    value: 12345n,
    dest: bob.address,
  })
  .signed({ sender: alice })
  .sent()
  .logStatus()
  .finalized()
- .events()
+ .events("Balances", "transfer")
  .run()
```

Currently, the way to achieve this involves `Extract`ing from the `Chain["call"]` union with a manual `Event<EventPhase, RuntimeEvent<PalletName>>` (notice this also required making Event-related types generic again). This approach is not ideal, neither in terms of maintainability nor checker performance.

A better approach would be to generate a lookup that supports our intended fluent API access patterns. The lookup...

```ts
import { Event } from "../primitives/mod.ts"

export type Chain = {
  pallets: Record<string, ChainPallet>
}
export type ChainPallet = {
  calls: Record<string, ChainCall>
  extras: Record<string, unknown>
  additional: Record<string, unknown>
  events: Record<string, Event>
  storageItems: Record<string, ChainStorageItem>
  storageMaps: Record<string, ChainStorageMap>
  constants: Record<string, unknown>
}
export interface ChainCall<Value extends Record<string, unknown> = Record<string, any>> {
  value: Value
}
export interface ChainStorageItem<Type = any> {
  type: Type
}
export interface ChainStorageMap<Keys extends unknown[] = any[], Type = any> {
  keys: Keys
  type: Type
}
```

Assuming this is the right path, do we even need to leverage `rune.unsafeAs` in the generated bindings? Does it meaningfully spare the checker of extra work?

**Comment by tjjfvi** [comment]
The new metadata shape will be conducive to being a generic. I'm not sure that threading a generic of the metadata through is the right solution, but it may be.

**Comment by harrysolovay** [comment]
> The new metadata shape will be conducive to being a generic

Nice! I suppose this will be relatively straightforward then: we could pass the `typeof metadata` instead of `C`, and then extract codec types as necessary.

**Comment by tjjfvi** [comment]
Yes, this was my thought for solving the dynamic side of the chain polymorphism. There's also, however, a question of the static side of chain polymorhpism, i.e. pattern libraries. Our current thought is to use import maps for this, but this only allows one chain to actually be used at runtime. Various solutions were proposed in #499 but I don't think any of them would work well. Ideally, the way we solve chain polymorphism for the dynamic and static sides could be unified.

**Comment by harrysolovay** [comment]
Agreed. What if we added a CLI command for generating a type stub of some sort (a limited `Chain` type that reflects only the capabilities needed by your pattern lib). This way, the pattern libs can ship with the minimum constraints, and then users will get type errors if they attempt to supply a client lacking those capabilities. Ie.

`pattern_lib.ts`

```ts
export type Client = {
  Multisig: {
    ...
  }
}

export class MyPatternRune<out U, out C extends Chain = Chain> extends Rune<T, U> {
  ...
}
```

`pattern_consumer.ts`

```ts
import { client } from "http://localhost:4646/frame/.../mod.ts"
import { MyPatternRune } from "./pattern_lib.ts"

const myPattern = MyPatternRune.from(client, T)
//                                   ~~~~~~
//                                   ^
//                                   will error out if unsupported
```
