### ISSUE TITLE
named codecs in codegen

### ISSUE THREAD

**Issue by harrysolovay** [paritytech/capi#572]
Currently, codecs are defined named with `$`-prefixed numbers. Should they instead have type-corresponding names?

**Comment by tjjfvi** [comment]
They [already do](https://capi.dev/@v0.1.0-beta.22/proxy/wss:rpc.polkadot.io/types/bitvec/order.ts#:~:text=export%20const%20%24lsb0%3A%20%24.Codec%3Ctypes.bitvec.order.Lsb0%3E%20%3D%20codecs.%24384). The `$123` definitions only serve to fix issues we would otherwise have with circularity.

**Comment by harrysolovay** [comment]
Missed that. EXTRAORDINARY!
