### ISSUE TITLE
rethink CLI / server instance reuse

### ISSUE THREAD

**Issue by harrysolovay** [paritytech/capi#582]
If a developer runs `main.ts --serve` and specifies a trailing `-- <command>`, then the process's life is limited to that of the command. In this case, it does not make sense to allow implicit reuse of the server, given that it could be shut down at any moment. We could allow implicit reuse in cases where the existing server was initialized without a command... but even this feels unclean imo.

**Comment by tjjfvi** [comment]
> If a developer runs main.ts --serve and specifies a trailing -- <command>, then the process's life is limited to that of the command. In this case, it does not make sense to allow implicit reuse of the server, given that it could be shut down at any moment.

This makes sense.

> We could allow implicit reuse in cases where the existing server was initialized without a command... but even this feels unclean imo.

Why? The point of running the server without a command is solely to have a long-running instance.

**Comment by harrysolovay** [comment]
Developers may forget that they already have a running instance open. This compromises the seemingly-reasonable potential expectation of a fresh dev net. I think it'd be best to go back to throwing a port-in-use error.

**Comment by tjjfvi** [comment]
> Developers may forget that they already have a running instance open.

If that's the concern, then the ctx command can print
```
Reusing existing capi server
```
when it does so

> I think it'd be best to go back to throwing a port-in-use error.

Spinning up a new testnet every time you run an example is extremely slow. A long-running instance of the capi server is an important part of the DX, and requiring separate command invocations depending on whether or not this is the case would be rather unergonomic.

Devs who are familiar with having dev servers running (e.g. metro for react native, misc for frontend) are used to the idea that they may have to restart the server for certain things to be reset.

**Comment by harrysolovay** [comment]
> requiring separate command invocations depending on whether or not this is the case would be rather unergonomic.

You make a good point. I agree.

Aside from the reuse log, are there any other ways that we might be able to insulate devs from possible pre-existing-server-instance confusion?

**Comment by harrysolovay** [comment]
@tjjfvi shall we close?
