### ISSUE TITLE
@capi/*: improve bundling for ESM

### ISSUE THREAD

**Issue by josepot** [paritytech/capi#59]
Improve and unify ESM/CJS `esbuild` bundles.

Make it
- bundler friendly `vite`, `webpack`, `parcel`, etc
- runtime friendly NodeJS

For inspiration check
- https://blog.isquaredsoftware.com/2023/08/esm-modernization-lessons/
- https://antfu.me/posts/publish-esm-and-cjs

**Comment by timbrinded** [comment]
I have found that [tsup](https://github.com/egoist/tsup) hugely simplified the task for me to dual publish ESM/CJS without the need for insane rollup configs or scripts. 

It can be annoying to convert a legacy project to it, so now is a great time to get it working before it becomes impossible in a few years!
