### ISSUE TITLE
`batchAll` example

### ISSUE THREAD

**Issue by harrysolovay** [paritytech/capi#592]
Showing off use of `Utility.batchAll`. Perhaps to only transfer from Bob to Charlie if an initial transfer from Alice to Bob succeeds?

**Comment by harrysolovay** [comment]
Ah, we're already using `batchAll`... I thought it was using `batch`. Perhaps we should colocate the two examples, and ensure that the `batchAll` example showcases the desire for sequential execution (or reversion).

**Comment by ryanleecode** [comment]
colocate as in in the same file?
