### ISSUE TITLE
metadata intersection

### ISSUE THREAD

**Issue by harrysolovay** [paritytech/capi#594]
A simple fn that accepts a list of `Metadata` and returns a new `Metadata`, which is the common intersection (to be used by pattern lib devs, who wish to target a specific combination of chains).

```ts
declare function metadataIntersection(...m: Metadata[]): Metadata
```

Perhaps we can use this to regularly regenerate some foundational types (`MultiAddress`, `Event`, (eventually) RPC types).

**Comment by ryanleecode** [comment]
Like an intersection between of the top level metadata fields? i.e.

```
metadata1 {
a
b
c
}

metadata2 {
a
d
e
}

metadataSubset([metadata1, metadata2]) -> { a }
```

**Comment by harrysolovay** [comment]
Somewhat: the means of determining the subset might be somewhat nuanced and won't apply solely to "top level fields." An example of this is union types: two unions types could share members with compatible discriminants, names and value types. In cases such as this, we can produce a new union type with just those compatible members (while excluding those incompatible).
