### ISSUE TITLE
support empty `target` in `PathInfo`

### ISSUE THREAD

**Issue by harrysolovay** [paritytech/capi#606]
Will be useful in cases where providers can infer the target. #597 is an example of this; the target can be inferred from the cwd. Within a Substrate workspace, one can create a script that interacts with a development build of the chain like so:

`playground.ts`

```ts
import { System } from "http://localhost:4646/frame/workspace/@latest/mod.ts"

console.log(System.Version)
```

> The location of this script inside of the Substrate workspace is irrelevant. Could be...
>
> - `workspace/a.ts`
> - `workspace/b/c.ts`
> - `workspace/d/e/f.ts`

```sh
deno run -A https://deno.land/x/capi/main.ts -- deno run -A -r playground.ts
```

**Comment by tjjfvi** [comment]
Should just be a matter of tweaking the regex.
