### ISSUE TITLE
star task not exiting in CI

### ISSUE THREAD

**Issue by harrysolovay** [paritytech/capi#627]
This has happened before (we were forgetting to explicitly close specific `Deno.run`-spawned processes. Now it seems there are many timer resources left open (preventing the unload event from firing). We could do a brute `Deno.exit`... but that's an admission of defeat to a leak.

**Comment by tjjfvi** [comment]
I've run star many times in #641, and they've all exited so far. Presuming fixed unless we observe otherwise.
