### ISSUE TITLE
test provider ready state progress indication

### ISSUE THREAD

**Issue by harrysolovay** [paritytech/capi#649]
Test providers should implement a `logProgress` method, which accepts the given provider's underlaying CLI process, and transforms its stdout into a simplified (and consistently-formatted) indication of the boot state. This is especially important for the zombienet and project providers, whose processes might take exorbitantly-long to boot.

- project provider `logProcess` can grab the Cargo compilation info
- In the case of Zombienet... it's a little less clear.

**Comment by tjjfvi** [comment]
Can you elaborate?

**Comment by harrysolovay** [comment]
Just updated the description

**Comment by harrysolovay** [comment]
We no longer have the provider model. Closing in favor of #861.
