### ISSUE TITLE
pattern library codegen story

### ISSUE THREAD

**Issue by harrysolovay** [paritytech/capi#656]
We can use the Capi server to generate chain-specific JSON schemas, which will enable pattern library developers to get autocompletion / easily specify the desired chain-specific constraint.

`constraint.jsonc`

```jsonc
{
  "$schema": "http://localhost:4646/frame/dev/polkadot/@latest/constraint.json",
  "constraints": {
    "Balances": {
      "calls": ["transfer"]
    },
    "System": {
      "storage": ["Account"]
    }
  }
}
```

Library developers can then import and utilize the `Chain` type corresponding to the contraint.

```ts
import { type Chain } from "http://localhost:4646/frame/constraint/constraint.json/mod.ts"

export interface MyType {
  something: string
}

export class MyTypeRune<out U, out C extends Chain = Chain> extends Rune<MyType, U> {
  constructor(_prime: MyTypeRune<U>["_prime"], readonly chain: ChainRune<U, C>) {
    super(_prime)
  }

  myMethod() {
    this.chain // utilize the narrowly-typed chain as you wish!
  }
}
```

This has the added benefit of (eventually) making Capi pattern libraries easily searchable / discoverable, as we know exactly which capabilities a given lib touches on by its JSON-defined constraint file.

**Comment by tjjfvi** [comment]
Closing in favor of #811
