### ISSUE TITLE
Concurrent execution of `zombienet` sometimes fail

### ISSUE THREAD

**Issue by kratico** [paritytech/capi#665]
## Bug Report

Concurrent `zombienet` bootstrapping seems to trigger this error https://github.com/paritytech/capi/actions/runs/4279205187/jobs/7449680066#step:8:45
which is related to how `zombienet` is packaged with `pkg` https://github.com/vercel/pkg/issues/1829

### Current Behavior

In `CI` the `Star` workflow timeouts. 

### Expected Behavior

In `CI` the `Star` workflow should not timeout or it should handle the error

**Comment by kratico** [comment]
a workaround could be to warm up `zombienet` with
```
zombienet-linux-x64 version
```
when the `ZombienetProvider` is created

**Comment by kratico** [comment]
perhaps it would be better to run `zombienet-xyz version` in the github action before executing the test script

**Comment by tjjfvi** [comment]
Fixed in #641 as we no longer use the CLI binary
