### ISSUE TITLE
`chain.extrinsic` -> `pallet.call`

### ISSUE THREAD

**Issue by harrysolovay** [paritytech/capi#667]
Currently, we do the following:

```ts
const call = chain.extrinsic(Rune.rec({
  type: palletName,
  value: Rune.rec({
    type: callName,
    ...callData
  })
}))
```

I believe something along the following lines would be preferable:

```ts
const call = chain
  .pallet(palletName)
  .call(callName)
  .apply(Rune.rec(callData))
```

> Note: this sample forgoes the (current) intermediate `.metadata()`, which will go away upon #641

**Comment by tjjfvi** [comment]
Closing per offline discussion
