### ISSUE TITLE
examples utilizing misc. kinds of signing

### ISSUE THREAD

**Issue by harrysolovay** [paritytech/capi#682]
The basic transfer example, only using a different signature type / means of signing. Perhaps https://deno.land/x/ed25519

Research involves looking into which test chains support a ed25519 scheme and how to run it w/ zombienet. 

implementation could involve modifying https://github.com/paritytech/capi/blob/main/crypto/Sr25519.ts to become a subclass that inherits a base class and adding a ED25519 subclass.

**Comment by harrysolovay** [comment]
The basic transfer example, only using a different signature type / means of signing. Perhaps https://deno.land/x/ed25519

**Comment by ryanleecode** [comment]
https://substrate.stackexchange.com/questions/6338/may-accounts-use-ed25519

this may prove useful

**Comment by ryanleecode** [comment]
Looks like we can just reuse the private keys as they both work in ed25519 and sr25519 world

```
import * as ed from "https://deno.land/x/ed25519/mod.ts"
import { encode } from "./crypto/hex.ts"
import { alice } from "./crypto/test_pairs.ts"

console.log(alice.secretKey.slice(32))
const publicKey = await ed.getPublicKey(alice.secretKey.slice(0, 32))

// 5AEA3946D01EDF878A07569CCE47EA04E397B03DA80AE42D62A24AEEAD62B8CD
console.log(encode(publicKey))
```

https://cyphr.me/ed25519_tool/ed.html

![image](https://user-images.githubusercontent.com/21375952/227364278-4890a294-9508-4034-9c22-8ae2cc96dcbe.png)
