### ISSUE TITLE
result-like API for tx event lists

### ISSUE THREAD

**Issue by nythrox** [paritytech/capi#693]
AFAIK, every extrinsic rpc call emits a function-specific `Event` when the rust function finalizes, for reference [lframe/uniques/src/lib.rs](https://github.com/paritytech/substrate/blob/master/frame/uniques/src/lib.rs#L276).

Many times this event comes with valuable info that we might need to later fetch and verify, or manually filter through the events.

Is it feasible to create a method such as `.send(signature)`, which emits the rpc call and returns with the value when call-specific event is emitted?

I believe it would be a good utility if we can correctly type it.

**Comment by harrysolovay** [comment]
Let's dig into this with a concrete example: say we're looking at the `Proxy.createPure` callable.

```ts
const finalizedEvents = Proxy
  .createPure({
    proxyType: "Any",
    delay: 0,
    index,
  })
  .signed({ sender })
  .sent()
  .finalizedEvents()
```

We may want to extract a *result* (either the successfully-created proxy id or the dispatch error) from `finalizedEvents`. We could create and use some common utils:

```diff
const finalizedEvents = Proxy
  .createPure({
    proxyType: "Any",
    delay: 0,
    index,
  })
  .signed({ sender })
  .sent()
  .finalizedEvents()
+ .pipe(unhandleDispatchError)
+ .map((events) => findPureCreatedEvent(events, index))
```

> Note: we don't bake in a final `.unhandle(undefined)`

Perhaps we could create a `result` method which abstracts over the three lines following `.sent()`.

```diff
const finalizedEvents = Proxy
  .createPure({
    proxyType: "Any",
    delay: 0,
    index,
  })
  .signed({ sender })
  .sent()
- .finalizedEvents()
- .pipe(unhandleDispatchError)
- .map((events) => findPureCreatedEvent(events, index))
+ .result((events) => findPureCreatedEvent(events, index))
```

> Note: `.result` could unhandle `undefined` and rehandle it with a `CouldNotFindResultEventError` (or another name).

@nythrox would it be reasonable to change the title of this issue to something like the following?: "result-like API for tx event lists"

**Comment by nythrox** [comment]
The `.result` nice to me. Do we know if the type information of these events are being emitted in the metadata? I've updated the link to the correct line

**Comment by tjjfvi** [comment]
Those events are included in the metadata, although their potential correlation with calls is not.

**Comment by nythrox** [comment]
How about a function on `EventsRune` that returns the first of a event (or errors): 

```diff
const collection = Proxy
  .createPure(...)
  .signed(...)
  .finalizedEvents()
+ .first(Event.Created)
  .access("collection")
```

That way you could easily access a specific event

**Comment by harrysolovay** [comment]
Closing in favor of #635
