### ISSUE TITLE
For node WebAssembly buffer size is larger than 4KB 

### ISSUE THREAD

**Issue by karl-kallavus** [paritytech/capi#700]
## Bug Report

When I import and use

`import { hashers } from 'capi'` for  `"capi": "0.1.0-beta.25"` in **node**

```
capi_crypto_wrappers.generated.js:2796 Uncaught RangeError: WebAssembly.Compile is disallowed on the main thread, if the buffer size is larger than 4KB. Use WebAssembly.compile, or compile on a worker thread.
    at instantiateInstance (capi_crypto_wrappers.generated.js:2796:22)
    at instantiateWithInstance (capi_crypto_wrappers.generated.js:333:22)
    at instantiate (capi_crypto_wrappers.generated.js:318:10)
    at lib.node.ts:3:6
```

### Steps To Reproduce

1. clone https://github.com/paritytech/capi-multisig-app
2. switch to `feat/idendticon` branch
3. `pnpm install`
4. `pnpm run dev`
5. open the app in browser and check console

source code: 
https://github.com/paritytech/capi-multisig-app/blob/feat/idendticon/src/components/identicon/utils/colors.tsx#L9

### Environment

- Node: v19.2.0
- capi: 0.1.0-beta.25

**Comment by ryanleecode** [comment]
@harrysolovay We need to do a release with this commit and it should be good: https://github.com/paritytech/capi/commit/0e38e4e3fa35e65c93873ae7c3220177eb35e325
