### ISSUE TITLE
`rune.emit`

### ISSUE THREAD

**Issue by harrysolovay** [paritytech/capi#706]
Let's consider the virtual multisig pattern.

```ts
const root = VirtualMultisigRune.deployment(chain, {
  founders: [alice.publicKey, bob.publicKey, charlie.publicKey],
  threshold: 2,
  deployer: alice,
})

await root.run()
```

Under the hood, this executes and awaits a sequence of extrinsics. Consumers of this pattern may like to know the pattern-specific statuses/step data as it plays out. Perhaps `iter` could return an async iterable of pattern-lib-defined events.

```ts
for await (const e of root.iter()) {
  e; // ProxiesCreated | ExistentialDeposits | OwnershipTransfers
}
```

Ideally, pattern libs devs could have some control over emissions.

```diff
const proxiesGrouped = Rune
  .tuple([proxies, membersCount])
  .map(([proxies, membersCount]) =>
    [proxies.slice(0, membersCount), proxies[membersCount]] as [Uint8Array[], Uint8Array]
  )
+ .emit((v) => new ProxiesCreated(v))
```

This likely requires altering the shape of the `Rune` type itself.

Implementation consideration aside: do we like the idea of an `emit`-like API? If so, what are some other considerations? Would we want to force `emit` usage to avoid patterns becoming black boxes? Might we want to support responses to emissions (such as attempting cancellation)? Should all extrinsic submission auto-emit?

**Comment by tjjfvi** [comment]
I don't think this is worthwhile to bake into rune – it's already quite type parameter heavy as is, and I think this would further complicate the mental model. These usecases can likely be addressed well with env once #517 is done.
