### ISSUE TITLE
Top-level await is not available for vite dev mode

### ISSUE THREAD

**Issue by karl-kallavus** [paritytech/capi#707]
## Bug Report

For `"capi": "0.1.0-beta.26"` there's an error after `pnpm run dev` in node

```
✘ [ERROR] Top-level await is not available in the configured target environment 
("chrome87", "edge88", "es2020", "firefox78", "safari14" + 2 overrides)

    node_modules/.pnpm/capi@0.1.0-beta.26/node_modules/capi/esm/deps_2/raw.githubusercontent.com/paritytech/capi-crypto-wrappers/14289c5/lib.js:2:0:
      2 │ await wasm.instantiate();
        ╵ ~~~~~
```

### Steps To Reproduce

1. clone https://github.com/paritytech/capi-multisig-app
2. switch to `feat/idendticon` branch
3. `pnpm install`
4. `pnpm run dev`
5. check the console

### Environment

- Node.js v19.2.0
- VITE v4.1.4
- capi: 0.1.0-beta.26

### Additional Information

- Possibly we need to set all targest to `esnext` (and for `capi-crypto-wrappers`)
e.g https://github.com/paritytech/capi/blob/main/_tasks/dnt.ts#L21
- I found a workaround for vite https://www.npmjs.com/package/vite-plugin-top-level-await

**Comment by statictype** [comment]
pleas see my answer [here](https://github.com/paritytech/capi-multisig-app/issues/77#issuecomment-1456011909)
