### ISSUE TITLE
make virtual multisig user proxying optional

### ISSUE THREAD

**Issue by harrysolovay** [paritytech/capi#733]
Do we want to enable this within the pattern itself?

**Comment by ryanleecode** [comment]
isnt this just the stash proxy example?

**Comment by ryanleecode** [comment]
We could but then what would the semantics be like for fundMemberProxy?

**Comment by ryanleecode** [comment]
Ill go with the error out approach then

**Comment by ryanleecode** [comment]
blocked by #761

**Comment by ryanleecode** [comment]
Instead of doing this we will add `fromHex` to `MultisigRune` since making user proxy optional may add too much complexity to `VirtualMultisigRune`.
