### ISSUE TITLE
chaining extrinsics without sending them

### ISSUE THREAD

**Issue by nythrox** [paritytech/capi#781]
Would it be feasible add a way to chain extrinsics before signing and sending them? 

This is useful especially for pattern libraries, but also in any situation where a user could want to put together a complex use-case (with conditional logic or data transformation) but only sign and send it later.
 
For example, if I wanted to make it easier to create a collection and return its data, I'd like to do the following:

```diff
const createCollection<X>(props: RunicArgs<X, CollectionProps>) => Nfts
    .create(props)
+   .into(ComposableExtrinsicRune) // sign and send later
    .finalized()
    .into(ValueRune)
    .map(findCreatedEvent)
    .access("collection")
    .chain(Nfts.Collection.value)
    .unhandle(undefined)
    .access(0)
 ```
```ts
const collection: Collection = createCollection(data).sign({ sender: alice }).send()
```

Without a similar function, I wouldn't be able have both the extrinsic and the data fetching (which depends on the id emitted from the extrinsics events) in the same utility function.

A single use-case would probably have to be split into different functions and have the user unite them:

```diff
const collectionId = 
+ createCollection(data)
  .sign({sender: alice})
  .send()
+ .pipe(extractCreatedCollectionId)
  
const collection =
+ findCollection(collectionId)

```  

This is a fairly simple use-case, but longer workflows that might be better abstracted away could benefit hugely from this.

Note: It's already possible to compose multiple extrinsics into a block using `Utility.batch`, but this doesn't allow for more complex use cases that depend on values from previous calls to use conditionals or transform the data

**Comment by harrysolovay** [comment]
I'd like to preface this with the possibility that I misunderstand the question/proposal:

> Would it be feasible add a way to chain extrinsics before signing and sending them?
>
> [...] to put together a complex use-case (with conditional logic or data transformation) but only sign and send it later.

Currently, we must sign each extrinsic, and there's no way to sign an extrinsic in the context of some dynamic conditions. However, we can eventually investigate a solution, in which wallets integrate with Capi and prompt end users to whitelist different kinds of extrinsics for managed signing (something like IAM policies / session keys). #629

If, however, you are describing the injection of a signer/signature into a pattern, this is another matter. Should be something we can address in the near future.

**Comment by nythrox** [comment]
Yes, the second one. I don't mean signing extrinsics dynamically, what I mean is being able to compose a chain of operations normally, and later have the user sign and send it (like in first example, which is not possible currently, but pretty much essential for building more complex pattern libraries)

**Comment by harrysolovay** [comment]
Closing in favor of #797
