### ISSUE TITLE
consuming pallets inside pattern libraries

### ISSUE THREAD

**Issue by nythrox** [paritytech/capi#783]
We should have a better way to consume pallets inside of pattern libraries 

The current way it's being done is by creating a raw extrinsic using `.unsafeAs<Chain.Call<C>>().into(ExtrinsicRune)`. Not only is it cumbersome to have to manually write every extrinsic you want to use, but it's prone to errors (untyped extrinsics) and it loses type information from possible errors (extrinsics built using the multisig pattern library instead of the codegenerated pallet will have `unknown` error generic param. There is also no guarantee the extrinsics will exist on the caller's chain.

Allowing pattern libraries to consume the codegenerated pallets would solve these issues, but I'm not sure about the drawbacks... maybe pattern libraries could be hardcoded to a pre-built chain, and get their version and typings from there?

Related #747

**Comment by nythrox** [comment]
> Pattern libraries can already use the codegenned factories

Is this... recommended? No problems? If so, I shouldn't have been manually writing extrinsics haha

**Comment by harrysolovay** [comment]
For now, we can use `unsafeAs` to tame the checker. It shouldn't be necessary once we've tackled constraints. For context, the definition and usage of a pattern lib's constraint may look like so:

```ts
import { Chain } from "capi"
import { Polkadot } from "@capi/polkadot"

// ...

export type MultisigChain<C extends Chain> =
  & Chain.Constraint<C>
  & Chain.PickStorage<Polkadot, "Multisig", "Multisigs">
  & Chain.PickCall<Polkadot, "Multisig", "asMulti" | "approveAsMulti" | "cancelAsMulti">

export class MultisigRune<out C extends Chain, out U>
  extends PatternRune<Multisig, MultisigChain<C>, U> {
  // ...
```

As you can see, we use the codegened types (contained within `Polkadot`) as the basis for selecting what our pattern needs accessible. From within the pattern, we can reference `this.chain`, which will be typed accordingly.

```ts
export class MultisigRune<out C extends Chain, out U>
  extends PatternRune<Multisig, MultisigChain<C>, U> {
  // ...

  no() {
    this.chain.pallet("DNE")
    //                ~~~~~
    //                ^
    //                type error
  }

  yes() {
    this.chain.pallet("Multisig")
  }
}
```

**Comment by nythrox** [comment]
Are the types from Polkadot generated in capi, or by the user? I'm not sure I fully understand how the separation of the user's chosen chain vs the pattern's pre-generated (?) chain would interplay

**Comment by harrysolovay** [comment]
Those types are Capi-generated. Aside from the generated pallet bindings, pattern lib devs can make use of all things codegened.

**Comment by nythrox** [comment]
Cool, from what I understood, this seems like a good way to let the pallets set their targets/constraints and still make use of codegen
