### ISSUE TITLE
StorageRune not working with optional partial keys

### ISSUE THREAD

**Issue by nythrox** [paritytech/capi#784]
Storages that have an optional partial key but then receive null as that key are throwing an error, expecting the non-null value:

```ts
Nfts.Collection
  .entryPageRaw(50, null)
  .run()
```

```
Uncaught (in promise) Unhandled {
  value: ScaleAssertError: typeof value !== "number"
```

**Comment by tjjfvi** [comment]
Have you rebased since #768?

**Comment by nythrox** [comment]
No, haven't rebased. Gonna test and then close here if fixed
