### ISSUE TITLE
Weird behaviour of `npm` package in VSCode 

### ISSUE THREAD

**Issue by statictype** [paritytech/capi#840]
Not sure it's a bug or i'm just missing something related to our monorepo setup.
I'm installing capi like so:
```
pnpm i -w capi https://capi.dev/@v0.1.0-beta.31/frame/wss/westend-rpc.polkadot.io/pkg.tar
```
In VSCode I get the following behaviour:
<img width="1066" alt="Screenshot 2023-04-04 at 15 38 41" src="https://user-images.githubusercontent.com/42985153/229811134-59b88276-7fa5-4d00-a227-74960a5374d8.png">

Adding a resolution in package.json seems to make VScode understand the module and type information

```ts
  "resolutions": {
    "@capi/polkadot_westend": "@capi/polkadot_westend"
  },
```
However, when running install again i get this error
```ts
 ERR_PNPM_BAD_PACKAGE_JSON  /Users/andreeaeftene/work/capi-multisig-app/node_modules/@capi/polkadot_westend/package.json: Invalid version: "latest"
```
Changing the version of the module's package.json to a valid semver seems to fix that.
Please let me know if there is a better approach for this.

**Comment by harrysolovay** [comment]
I don't believe `@capi/polkadot_westend` is a valid generated package name, although I could be mistaken. Does it exist in your `node_modules`? If so, can you please share your tsconfig?

**Comment by statictype** [comment]
the package was introduced [here](https://github.com/paritytech/capi-multisig-app/pull/113/files) with a different name.
probably the name changed recently.
all good with `@capi/westend`
