### ISSUE TITLE
Typescript autocompletion is laggy in VSCode

### ISSUE THREAD

**Issue by kratico** [paritytech/capi#849]
This is probably related to an update in the last 2 weeks

**Comment by harrysolovay** [comment]
I'm also experiencing this problem.

https://user-images.githubusercontent.com/4893548/230730484-d24414b0-a3db-413c-ac18-a23e666b2d9e.mov

There are two related open issues:

- denoland/vscode_deno#824
- denoland/vscode_deno#825

I'd also imagine that this has something to do with LSP erroring out with the following mish mash on repeat:

```
Unable to send result to client.
successfully cancelled request with ID: 155
client asked to cancel request 153, but no such pending request exists, ignoring
```

These logs appear in denoland/deno#18494, which ultimately doesn't address editor responsiveness issues.

Things attempted

- disabling shiki
- emptying the Deno cache
- setting a new loc for the Deno cache
- loading old versions of Capi

**Comment by harrysolovay** [comment]
Explicitly setting all `enablePaths`––except for `examples`––in `.vscode/settings.json` solves it. This ofc is a bad solution for us, as we frequently develop against / debug via examples.
