### ISSUE TITLE
Check formatting in CI and error if incorrect

### ISSUE THREAD

**Issue by tjjfvi** [paritytech/capi#85]
Alternatively, should it fix and commit?

**Comment by harrysolovay** [comment]
Sure, perhaps using a workflow similar to UDD, with a [create PR step](https://github.com/paritytech/capi/blob/7e6876699068b5e27bb0a97dac740ed7185cb6c6/.github/workflows/udd.yml#L20-L30).

**Comment by tjjfvi** [comment]
Most of the time, it would be checking an existing PR, in which case I think it should just commit on top.

**Comment by tjjfvi** [comment]
Moving the auto-updating part of #104
