### ISSUE TITLE
make RunicArgs handle nested parameters

### ISSUE THREAD

**Issue by nythrox** [paritytech/capi#850]
Nested object parameters don't get runified with RunicArgs:
```
type Foo = { a?: number, b?: { c?: { d?: number } } }
// RunicArgs<X, Foo> becomes
{ 
  a:  number | Rune<number | undefined, X> | undefined,
  b?: { c?: { d?: number } } | Rune<{ c?: { d?: number } }, X> | undefined
}
```

This makes it harder both for the consumer of a Runified function and of the creator:
As a user, I have to add a pyramid of Rune.rec if I want to feed a Rune value to nested parameters
```diff
Nfts
  .create({
-   config: Rune.rec({
      settings: DefaultCollectionSetting.allOff,
-     mintSettings: Rune.rec({
        mintType: MintType.Issuer(), // Rune<MintType>
        defaultItemSettings: DefaultItemSetting.allOn,
      }),
    }),
    admin: alice.address,
  })
```
As the function creator, it's hard to deal with possible undefined values in nested parameters
```ts
const { b }  = RunicArgs.resolve(props)
const d = b?.access("c").unhandle(undefined).access("d") // error: Type 'string' is not assignable to type 'Rune<never, never>' (Type "c" is not found on undefined)
```
The Rune.rec thing is also confusing for new users who don't know why they need to runify their already rune parameters to consume a pallet.

We could create an optional `RunicArgs.rec` to handle nested object params, and it should be used by default in pallet libraries. 

---

unrelated question... should we be naming our parameter types as Props while we pass them through RunicArgs? Should it be RunicProps or Args? :)

**Comment by nythrox** [comment]
@tjjfvi @harrysolovay I can implement this, just need some thoughts on how it should look (is it a good idea? is there something I'm missing?)

**Comment by harrysolovay** [comment]
I don't think we want to take this on considering that most users will use factories from codegen (in which case, this shouldn't pose any difficulty).
