### ISSUE TITLE
Investigate devnet parachain not producing blocks

### ISSUE THREAD

**Issue by kratico** [paritytech/capi#872]
The following configuration in `capi.config.ts` does not produce blocks in `westmint`

Reproduced in OSX

```
rococoDev: {
      binary: polkadot,
      chain: "rococo-local",
      parachains: {
        statemine: {
          id: 1000,
          binary: polkadotParachain,
          chain: "statemine-local",
        },
        contracts: {
          id: 2000,
          binary: polkadotParachain,
          chain: "contracts-rococo-local",
        },
        westmint: {
          id: 3000,
          binary: polkadotParachain,
          chain: "westmint-local",
        },
      },
    },

**Comment by kratico** [comment]
@tjjfvi @harrysolovay the issue is that we need at least 1 validator per parachain.
The 2nd issue is that only `alice` and `bob` have well known keys.

I'll investigate how to update the chain spec to include more validators following https://docs.substrate.io/tutorials/build-a-blockchain/authorize-specific-nodes/

**Comment by tjjfvi** [comment]
> The 2nd issue is that only alice and bob have well known keys.

Can you clarify what this means?

**Comment by kratico** [comment]
@tjjfvi only `alice` and `bob` are authorized to produce blocks.
To add more authorized validate the genesis in the chain spec needs to be updated.
