### ISSUE TITLE
examples timing out on main

### ISSUE THREAD

**Issue by tjjfvi** [paritytech/capi#880]
https://github.com/paritytech/capi/actions/runs/4681427980/jobs/8294057187

As of #878

(I've now added `Examples (Deno)` to the required workflows for merge)

**Comment by kratico** [comment]
It seems that it started a commit before in #876 

See https://github.com/paritytech/capi/actions/workflows/checks.yml?query=branch%3Amain

@harrysolovay Shall we comment exclude again the smoldot example?

**Comment by harrysolovay** [comment]
Yea, I think that makes the most sense

**Comment by kratico** [comment]
fixed by #890
