### ISSUE TITLE
Change discriminant from `_tag` to `type`

### ISSUE THREAD

**Issue by tjjfvi** [paritytech/capi#93]
`type` isn't a valid Rust identifier (unless escaped via `r#type`), so this minimizes chance of collision.

**Comment by harrysolovay** [comment]
Let's make sure to update the examples in [`_docs/Types.md`](https://github.com/paritytech/capi/blob/7e6876699068b5e27bb0a97dac740ed7185cb6c6/_docs/Types.md) as well
