### ISSUE TITLE
pattern libraries are not discoverable

### ISSUE THREAD

**Issue by ryanleecode** [paritytech/capi#931]
~~In most examples we have this `import { signature } from "capi/patterns/signature/polkadot.ts"` but with the published version of capi I cannot find signature import.~~

~~`import { signature } from 'capi' --> Module '"capi"' has no exported member 'signature'.`~~

---

Anything under "capi/patterns" cannot be discovered by intellisense.

**Comment by tjjfvi** [comment]
In node,
```ts
import { signature } from "capi/patterns/signature/polkadot"
```

**Comment by ryanleecode** [comment]
Looks like it does work but lacks discoverability.

**Comment by ryanleecode** [comment]
This video shows what I mean by lack of discoverability

https://user-images.githubusercontent.com/21375952/234687404-3800e8e2-e809-422b-9127-d5ce0c4502fd.mp4

**Comment by harrysolovay** [comment]
@ryanleecode are you sure this is Capi-specific, as opposed to a current limitation of TypeScript's LS implementation?

**Comment by harrysolovay** [comment]
#54330
