### ISSUE TITLE
upgrading capi in pnpm projects doesn't clean up old node modules

### ISSUE THREAD

**Issue by ryanleecode** [paritytech/capi#938]
![image](https://user-images.githubusercontent.com/21375952/234905956-cd6ed02e-1f1c-450c-9b0d-81cd38f7e645.png)

When upgrading capi in a pnpm project, it doesn't clean up the artifacts located under `node_modules/.pnpm`. In the picture above you can see there are both 0.35 and 0.36 tar folders. 

This doesn't happen in a regular npm project, only pnpm. 

Since there are two folders of the same package, intellisense can get confused and still use the types from the old package, so the user needs to manually delete the old version themselves.

Should `capi sync` remove these extraneous files?

**Comment by harrysolovay** [comment]
Per an offline convo with @ryanleecode, this appears not to be an issue with Capi (it's PNPM behavior).

**Comment by harrysolovay** [comment]
For future readers: try nuking the `node_modules` and reinstalling with the `--force` flag. If you run into problems, please open a new issue.
