### ISSUE TITLE
CAPI CLI DX

### ISSUE THREAD

**Issue by kratico** [paritytech/capi#940]
Improve CLI DX by supporting
- extra args, like `--help`
- subcommands help
- subcommands args help
- other...

**Comment by harrysolovay** [comment]
I think it would make sense to have subcommands for the targets of `sync`. Ie. `sync node` and `sync deno`. This would allow us to tailor each command with additional flags representing target specifics (such as `--clean`, in the case of #938).

**Comment by kratico** [comment]
I'm considering https://cliffy.io/ instead of Deno std [flags](https://deno.land/std@0.185.0/flags/mod.ts)

Thoughts?
